/*
 Highcharts 4.0.4 JS v/Highstock 2.0.4 (2014-09-02)

 Standalone Highcharts Framework

 License: MIT License
 Highcharts 4.0.4 JS v/Highstock 2.0.4 (2014-09-02)

 (c) 2009-2014 Torstein Honsi

 License: www.highcharts.com/license
*/
var HighchartsAdapter=function(){function u(n){function q(p,l,m){p.removeEventListener(l,m,!1)}function p(p,l,m){m=p.HCProxiedMethods[m.toString()];p.detachEvent("on"+l,m)}function m(m,l){var n=m.HCEvents,u,s,A;if(m.removeEventListener)u=q;else if(m.attachEvent)u=p;else return;l?(s={},s[l]=!0):s=n;for(A in s)if(n[A])for(s=n[A].length;s--;)u(m,A,n[A][s])}n.HCExtended||Highcharts.extend(n,{HCExtended:!0,HCEvents:{},bind:function(p,l){var m=this,q=this.HCEvents,n;m.addEventListener?m.addEventListener(p,
l,!1):m.attachEvent&&(n=function(p){p.target=p.srcElement||window;l.call(m,p)},m.HCProxiedMethods||(m.HCProxiedMethods={}),m.HCProxiedMethods[l.toString()]=n,m.attachEvent("on"+p,n));q[p]===A&&(q[p]=[]);q[p].push(l)},unbind:function(n,l){var u,s;n?(u=this.HCEvents[n]||[],l?(s=HighchartsAdapter.inArray(l,u),-1<s&&(u.splice(s,1),this.HCEvents[n]=u),this.removeEventListener?q(this,n,l):this.attachEvent&&p(this,n,l)):(m(this,n),this.HCEvents[n]=[])):(m(this),this.HCEvents={})},trigger:function(p,l){var m=
this.HCEvents[p]||[],q=m.length,n,u,s;u=function(){l.defaultPrevented=!0};for(n=0;n<q;n++){s=m[n];if(l.stopped)break;l.preventDefault=u;l.target=this;l.type||(l.type=p);!1===s.call(this,l)&&l.preventDefault()}}});return n}var A,s=document,W=[],y=[],aa,N={},ea;Math.easeInOutSine=function(n,q,p,m){return-p/2*(Math.cos(Math.PI*n/m)-1)+q};return{init:function(n){s.defaultView||(this._getStyle=function(q,p){var m;if(q.style[p])return q.style[p];"opacity"===p&&(p="filter");m=q.currentStyle[p.replace(/\-(\w)/g,
function(p,l){return l.toUpperCase()})];"filter"===p&&(m=m.replace(/alpha\(opacity=([0-9]+)\)/,function(p,l){return l/100}));return""===m?1:m},this.adapterRun=function(q,p){var m={width:"clientWidth",height:"clientHeight"}[p];if(m)return q.style.zoom=1,q[m]-2*parseInt(HighchartsAdapter._getStyle(q,"padding"),10)});Array.prototype.forEach||(this.each=function(q,p){for(var m=0,n=q.length;m<n;m++)if(!1===p.call(q[m],q[m],m,q))return m});Array.prototype.indexOf||(this.inArray=function(q,p){var m,n=0;
if(p)for(m=p.length;n<m;n++)if(p[n]===q)return n;return-1});Array.prototype.filter||(this.grep=function(q,p){for(var m=[],n=0,l=q.length;n<l;n++)p(q[n],n)&&m.push(q[n]);return m});ea=function(n,p,m){this.options=p;this.elem=n;this.prop=m};ea.prototype={update:function(){var q;q=this.paths;var p=this.elem,m=p.element;if(N[this.prop])N[this.prop](this);else q&&m?p.attr("d",n.step(q[0],q[1],this.now,this.toD)):p.attr?m&&p.attr(this.prop,this.now):(q={},q[this.prop]=this.now+this.unit,Highcharts.css(p,
q));this.options.step&&this.options.step.call(this.elem,this.now,this)},custom:function(n,p,m){var u=this,l=function(l){return u.step(l)},s;this.startTime=+new Date;this.start=n;this.end=p;this.unit=m;this.now=this.start;this.pos=this.state=0;l.elem=this.elem;l()&&1===y.push(l)&&(aa=setInterval(function(){for(s=0;s<y.length;s++)y[s]()||y.splice(s--,1);y.length||clearInterval(aa)},13))},step:function(n){var p=+new Date,m;m=this.options;var s=this.elem,l;if(s.stopAnimation||s.attr&&!s.element)m=!1;
else if(n||p>=m.duration+this.startTime){this.now=this.end;this.pos=this.state=1;this.update();n=this.options.curAnim[this.prop]=!0;for(l in m.curAnim)!0!==m.curAnim[l]&&(n=!1);n&&m.complete&&m.complete.call(s);m=!1}else s=p-this.startTime,this.state=s/m.duration,this.pos=m.easing(s,0,1,m.duration),this.now=this.start+(this.end-this.start)*this.pos,this.update(),m=!0;return m}};this.animate=function(q,p,m){var s,l="",u,A,y;q.stopAnimation=!1;if("object"!==typeof m||null===m)s=arguments,m={duration:s[2],
easing:s[3],complete:s[4]};"number"!==typeof m.duration&&(m.duration=400);m.easing=Math[m.easing]||Math.easeInOutSine;m.curAnim=Highcharts.extend({},p);for(y in p)A=new ea(q,m,y),u=null,"d"===y?(A.paths=n.init(q,q.d,p.d),A.toD=p.d,s=0,u=1):q.attr?s=q.attr(y):(s=parseFloat(HighchartsAdapter._getStyle(q,y))||0,"opacity"!==y&&(l="px")),u||(u=p[y]),A.custom(s,u,l)}},_getStyle:function(n,q){return window.getComputedStyle(n,void 0).getPropertyValue(q)},addAnimSetter:function(n,q){N[n]=q},getScript:function(n,
q){var p=s.getElementsByTagName("head")[0],m=s.createElement("script");m.type="text/javascript";m.src=n;m.onload=q;p.appendChild(m)},inArray:function(n,q){return q.indexOf?q.indexOf(n):W.indexOf.call(q,n)},adapterRun:function(n,q){return parseInt(HighchartsAdapter._getStyle(n,q),10)},grep:function(n,q){return W.filter.call(n,q)},map:function(n,q){for(var p=[],m=0,s=n.length;m<s;m++)p[m]=q.call(n[m],n[m],m,n);return p},offset:function(n){var q=document.documentElement;n=n.getBoundingClientRect();return{top:n.top+
(window.pageYOffset||q.scrollTop)-(q.clientTop||0),left:n.left+(window.pageXOffset||q.scrollLeft)-(q.clientLeft||0)}},addEvent:function(n,q,p){u(n).bind(q,p)},removeEvent:function(n,q,p){u(n).unbind(q,p)},fireEvent:function(n,q,p,m){var u;s.createEvent&&(n.dispatchEvent||n.fireEvent)?(u=s.createEvent("Events"),u.initEvent(q,!0,!0),u.target=n,Highcharts.extend(u,p),n.dispatchEvent?n.dispatchEvent(u):n.fireEvent(q,u)):!0===n.HCExtended&&(p=p||{},n.trigger(q,p));p&&p.defaultPrevented&&(m=null);m&&m(p)},
washMouseEvent:function(n){return n},stop:function(n){n.stopAnimation=!0},each:function(n,q){return Array.prototype.forEach.call(n,q)}}}();
(function(){function u(a,b){var c;a||(a={});for(c in b)a[c]=b[c];return a}function A(){var a,b=arguments,c,d={},e=function(a,b){var c,d;"object"!==typeof a&&(a={});for(d in b)b.hasOwnProperty(d)&&((c=b[d])&&"object"===typeof c&&"[object Array]"!==Object.prototype.toString.call(c)&&"renderTo"!==d&&"number"!==typeof c.nodeType?a[d]=e(a[d]||{},c):a[d]=b[d]);return a};!0===b[0]&&(d=b[1],b=Array.prototype.slice.call(b,2));c=b.length;for(a=0;a<c;a++)d=e(d,b[a]);return d}function s(a,b){return parseInt(a,
b||10)}function W(a){return"string"===typeof a}function y(a){return a&&"object"===typeof a}function aa(a){return"[object Array]"===Object.prototype.toString.call(a)}function N(a){return"number"===typeof a}function ea(a){return G.log(a)/G.LN10}function n(a){return G.pow(10,a)}function q(a,b){for(var c=a.length;c--;)if(a[c]===b){a.splice(c,1);break}}function p(a){return a!==C&&null!==a}function m(a,b,c){var d,e;if(W(b))p(c)?a.setAttribute(b,c):a&&a.getAttribute&&(e=a.getAttribute(b));else if(p(b)&&
y(b))for(d in b)a.setAttribute(d,b[d]);return e}function la(a){return aa(a)?a:[a]}function l(){var a=arguments,b,c,d=a.length;for(b=0;b<d;b++)if(c=a[b],c!==C&&null!==c)return c}function P(a,b){ha&&!Q&&b&&b.opacity!==C&&(b.filter="alpha(opacity="+100*b.opacity+")");u(a.style,b)}function ma(a,b,c,d,e){a=D.createElement(a);b&&u(a,b);e&&P(a,{padding:0,border:"none",margin:0});c&&P(a,c);d&&d.appendChild(a);return a}function Pa(a,b){var c=function(){return C};c.prototype=new a;u(c.prototype,b);return c}
function $(a,b,c,d){var e=ba.numberFormat,f=F.lang,g=+a||0,h=-1===b?(g.toString().split(".")[1]||"").length:isNaN(b=X(b))?2:b,k=void 0===c?f.decimalPoint:c,f=void 0===d?f.thousandsSep:d,v=0>g?"-":"",z=String(s(g=X(g).toFixed(h))),w=3<z.length?z.length%3:0;return e!==$?e(a,b,c,d):v+(w?z.substr(0,w)+f:"")+z.substr(w).replace(/(\d{3})(?=\d)/g,"$1"+f)+(h?k+X(g-z).toFixed(h).slice(2):"")}function da(a,b){return Array((b||2)+1-String(a).length).join(0)+a}function Qa(a,b,c){var d=a[b];a[b]=function(){var a=
Array.prototype.slice.call(arguments);a.unshift(d);return c.apply(this,a)}}function sa(a,b){for(var c="{",d=!1,e,f,g,h,k,v=[];-1!==(c=a.indexOf(c));){e=a.slice(0,c);if(d){f=e.split(":");g=f.shift().split(".");k=g.length;e=b;for(h=0;h<k;h++)e=e[g[h]];f.length&&(f=f.join(":"),g=/\.([0-9])/,h=F.lang,k=void 0,/f$/.test(f)?(k=(k=f.match(g))?k[1]:-1,null!==e&&(e=$(e,k,h.decimalPoint,-1<f.indexOf(",")?h.thousandsSep:""))):e=ta(f,e))}v.push(e);a=a.slice(c+1);c=(d=!d)?"}":"{"}v.push(a);return v.join("")}function jb(a,
b,c,d){var e;c=l(c,1);e=a/c;b||(b=[1,2,2.5,5,10],!1===d&&(1===c?b=[1,2,5,10]:.1>=c&&(b=[1/c])));for(d=0;d<b.length&&!(a=b[d],e<=(b[d]+(b[d+1]||b[d]))/2);d++);return a*c}function Ea(a,b){var c=a.length,d,e;for(e=0;e<c;e++)a[e].ss_i=e;a.sort(function(a,c){d=b(a,c);return 0===d?a.ss_i-c.ss_i:d});for(e=0;e<c;e++)delete a[e].ss_i}function ua(a){for(var b=a.length,c=a[0];b--;)a[b]<c&&(c=a[b]);return c}function na(a){for(var b=a.length,c=a[0];b--;)a[b]>c&&(c=a[b]);return c}function va(a,b){for(var c in a)a[c]&&
a[c]!==b&&a[c].destroy&&a[c].destroy(),delete a[c]}function wa(a){xa||(xa=ma("div"));a&&xa.appendChild(a);xa.innerHTML=""}function Y(a){return parseFloat(a.toPrecision(14))}function Ra(){var a=F.global.useUTC,b=a?"getUTC":"get";Sa=F.global.Date||window.Date;Ta=6E4*(a&&F.global.timezoneOffset||0);Ua=b+"Minutes";Va=b+"Hours";Wa=b+"Day";Xa=b+"Date";Ya=b+"Month";Za=b+"FullYear"}function I(){}function ia(a,b,c,d){this.axis=a;this.pos=b;this.type=c||"";this.isNew=!0;c||d||this.addLabel()}function ya(){this.init.apply(this,
arguments)}function Fa(){this.init.apply(this,arguments)}var C,D=document,H=window,G=Math,B=G.round,R=G.floor,ja=G.ceil,x=G.max,U=G.min,X=G.abs,oa=G.cos,za=G.sin,$a=G.PI,ab=2*$a/360,fa=navigator.userAgent,kb=H.opera,ha=/msie/i.test(fa)&&!kb,lb=/AppleWebKit/.test(fa),Aa=/Firefox/.test(fa),bb=/(Mobile|Android|Windows Phone)/.test(fa),Q=!!D.createElementNS&&!!D.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect,mb=Aa&&4>parseInt(fa.split("Firefox/")[1],10),Z=!Q&&!ha&&!!D.createElement("canvas").getContext,
cb={},Ga=0,xa,F,ta,S,Ha,O,ga=[],db=0,nb=/^[0-9]+$/,Sa,Ta,Ua,Va,Wa,Xa,Ya,Za,pa={},ba;H.Highcharts?O(16,!0):ba=H.Highcharts={};ta=function(a,b,c){if(!p(b)||isNaN(b))return"Invalid date";a=l(a,"%Y-%m-%d %H:%M:%S");var d=new Sa(b-Ta),e,f=d[Va](),g=d[Wa](),h=d[Xa](),k=d[Ya](),v=d[Za](),z=F.lang,w=z.weekdays,d=u({a:w[g].substr(0,3),A:w[g],d:da(h),e:h,b:z.shortMonths[k],B:z.months[k],m:da(k+1),y:v.toString().substr(2,2),Y:v,H:da(f),I:da(f%12||12),l:f%12||12,M:da(d[Ua]()),p:12>f?"AM":"PM",P:12>f?"am":"pm",
S:da(d.getSeconds()),L:da(B(b%1E3),3)},ba.dateFormats);for(e in d)for(;-1!==a.indexOf("%"+e);)a=a.replace("%"+e,"function"===typeof d[e]?d[e](b):d[e]);return c?a.substr(0,1).toUpperCase()+a.substr(1):a};O=function(a,b){var c="Highcharts error #"+a+": www.highcharts.com/errors/"+a;if(b)throw c;H.console&&console.log(c)};Ha={init:function(a,b,c){b=b||"";var d=a.shift,e=-1<b.indexOf("C"),f=e?7:3,g;b=b.split(" ");c=[].concat(c);var h,k,v=function(a){for(g=a.length;g--;)"M"===a[g]&&a.splice(g+1,0,a[g+
1],a[g+2],a[g+1],a[g+2])};e&&(v(b),v(c));a.isArea&&(h=b.splice(b.length-6,6),k=c.splice(c.length-6,6));if(d<=c.length/f&&b.length===c.length)for(;d--;)c=[].concat(c).splice(0,f).concat(c);a.shift=0;if(b.length)for(a=c.length;b.length<a;)d=[].concat(b).splice(b.length-f,f),e&&(d[f-6]=d[f-2],d[f-5]=d[f-1]),b=b.concat(d);h&&(b=b.concat(h),c=c.concat(k));return[b,c]},step:function(a,b,c,d){var e=[],f=a.length;if(1===c)e=d;else if(f===b.length&&1>c)for(;f--;)d=parseFloat(a[f]),e[f]=isNaN(d)?a[f]:c*parseFloat(b[f]-
d)+d;else e=b;return e}};var Ba=H.HighchartsAdapter,V=Ba||{};Ba&&Ba.init.call(Ba,Ha);var Ca=V.adapterRun,ob=V.inArray,t=V.each,eb=V.grep,fb=V.map,L=V.addEvent,T=V.removeEvent,M=V.fireEvent,gb=V.animate,Ia=V.stop,Ja={enabled:!0,x:0,y:15,style:{color:"#606060",cursor:"default",fontSize:"11px"}};F={colors:"#7cb5ec #434348 #90ed7d #f7a35c #8085e9 #f15c80 #e4d354 #8085e8 #8d4653 #91e8e1".split(" "),symbols:["circle","diamond","square","triangle","triangle-down"],lang:{loading:"Loading...",months:"January February March April May June July August September October November December".split(" "),
shortMonths:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),weekdays:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),decimalPoint:".",numericSymbols:"kMGTPE".split(""),resetZoom:"Reset zoom",resetZoomTitle:"Reset zoom level 1:1",thousandsSep:","},global:{useUTC:!0,canvasToolsURL:"http://code.highcharts.com@product.cdnpath@//Highstock 2.0.4/modules/canvas-tools.js",VMLRadialGradientURL:"http://code.highcharts.com@product.cdnpath@//Highstock 2.0.4/gfx/vml-radial-gradient.png"},
chart:{borderColor:"#4572A7",borderRadius:0,defaultSeriesType:"line",ignoreHiddenSeries:!0,spacing:[10,10,15,10],backgroundColor:"#FFFFFF",plotBorderColor:"#C0C0C0",resetZoomButton:{theme:{zIndex:20},position:{align:"right",x:-10,y:10}}},title:{text:"Chart title",align:"center",margin:15,style:{color:"#333333",fontSize:"18px"}},subtitle:{text:"",align:"center",style:{color:"#555555"}},plotOptions:{line:{allowPointSelect:!1,showCheckbox:!1,animation:{duration:1E3},events:{},lineWidth:2,marker:{lineWidth:0,
radius:4,lineColor:"#FFFFFF",states:{hover:{enabled:!0,lineWidthPlus:1,radiusPlus:2},select:{fillColor:"#FFFFFF",lineColor:"#000000",lineWidth:2}}},point:{events:{}},dataLabels:A(Ja,{align:"center",enabled:!1,formatter:function(){return null===this.y?"":$(this.y,-1)},verticalAlign:"bottom",y:0}),cropThreshold:300,pointRange:0,states:{hover:{lineWidthPlus:1,marker:{},halo:{size:10,opacity:.25}},select:{marker:{}}},stickyTracking:!0,turboThreshold:1E3}},labels:{style:{position:"absolute",color:"#3E576F"}},
legend:{enabled:!0,align:"center",layout:"horizontal",labelFormatter:function(){return this.name},borderColor:"#909090",borderRadius:0,navigation:{activeColor:"#274b6d",inactiveColor:"#CCC"},shadow:!1,itemStyle:{color:"#333333",fontSize:"12px",fontWeight:"bold"},itemHoverStyle:{color:"#000"},itemHiddenStyle:{color:"#CCC"},itemCheckboxStyle:{position:"absolute",width:"13px",height:"13px"},symbolPadding:5,verticalAlign:"bottom",x:0,y:0,title:{style:{fontWeight:"bold"}}},loading:{labelStyle:{fontWeight:"bold",
position:"relative",top:"45%"},style:{position:"absolute",backgroundColor:"white",opacity:.5,textAlign:"center"}},tooltip:{enabled:!0,animation:Q,backgroundColor:"rgba(249, 249, 249, .85)",borderWidth:1,borderRadius:3,dateTimeLabelFormats:{millisecond:"%A, %b %e, %H:%M:%S.%L",second:"%A, %b %e, %H:%M:%S",minute:"%A, %b %e, %H:%M",hour:"%A, %b %e, %H:%M",day:"%A, %b %e, %Y",week:"Week from %A, %b %e, %Y",month:"%B %Y",year:"%Y"},headerFormat:'<span style="font-size: 10px">{point.key}</span><br/>',
pointFormat:'<span style="color:{series.color}">\u25cf</span> {series.name}: <b>{point.y}</b><br/>',shadow:!0,snap:bb?25:10,style:{color:"#333333",cursor:"default",fontSize:"12px",padding:"8px",whiteSpace:"nowrap"}},credits:{enabled:!0,text:"Highcharts.com",href:"http://www.highcharts.com",position:{align:"right",x:-10,verticalAlign:"bottom",y:-5},style:{cursor:"pointer",color:"#909090",fontSize:"9px"}}};var Ka=F.plotOptions;Ra();var pb=/rgba\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]?(?:\.[0-9]+)?)\s*\)/,
qb=/#([a-fA-F0-9]{2})([a-fA-F0-9]{2})([a-fA-F0-9]{2})/,rb=/rgb\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*\)/,qa=function(a){var b=[],c,d;(function(a){a&&a.stops?d=fb(a.stops,function(a){return qa(a[1])}):(c=pb.exec(a))?b=[s(c[1]),s(c[2]),s(c[3]),parseFloat(c[4],10)]:(c=qb.exec(a))?b=[s(c[1],16),s(c[2],16),s(c[3],16),1]:(c=rb.exec(a))&&(b=[s(c[1]),s(c[2]),s(c[3]),1])})(a);return{get:function(c){var f;d?(f=A(a),f.stops=[].concat(f.stops),t(d,function(a,b){f.stops[b]=[f.stops[b][0],a.get(c)]})):
f=b&&!isNaN(b[0])?"rgb"===c?"rgb("+b[0]+","+b[1]+","+b[2]+")":"a"===c?b[3]:"rgba("+b.join(",")+")":a;return f},brighten:function(a){if(d)t(d,function(b){b.brighten(a)});else if(N(a)&&0!==a){var c;for(c=0;3>c;c++)b[c]+=s(255*a),0>b[c]&&(b[c]=0),255<b[c]&&(b[c]=255)}return this},rgba:b,setOpacity:function(a){b[3]=a;return this}}};I.prototype={opacity:1,textProps:"fontSize fontWeight fontFamily color lineHeight width textDecoration textShadow HcTextStroke".split(" "),init:function(a,b){this.element=
"span"===b?ma(b):D.createElementNS("http://www.w3.org/2000/svg",b);this.renderer=a},animate:function(a,b,c){b=l(b,S,!0);Ia(this);b?(b=A(b,{}),c&&(b.complete=c),gb(this,a,b)):(this.attr(a),c&&c());return this},colorGradient:function(a,b,c){var d=this.renderer,e,f,g,h,k,v,z,w,E,r,l=[];a.linearGradient?f="linearGradient":a.radialGradient&&(f="radialGradient");if(f){g=a[f];h=d.gradients;v=a.stops;E=c.radialReference;aa(g)&&(a[f]=g={x1:g[0],y1:g[1],x2:g[2],y2:g[3],gradientUnits:"userSpaceOnUse"});"radialGradient"===
f&&E&&!p(g.gradientUnits)&&(g=A(g,{cx:E[0]-E[2]/2+g.cx*E[2],cy:E[1]-E[2]/2+g.cy*E[2],r:g.r*E[2],gradientUnits:"userSpaceOnUse"}));for(r in g)"id"!==r&&l.push(r,g[r]);for(r in v)l.push(v[r]);l=l.join(",");h[l]?a=h[l].attr("id"):(g.id=a="highcharts-"+Ga++,h[l]=k=d.createElement(f).attr(g).add(d.defs),k.stops=[],t(v,function(a){0===a[1].indexOf("rgba")?(e=qa(a[1]),z=e.get("rgb"),w=e.get("a")):(z=a[1],w=1);a=d.createElement("stop").attr({offset:a[0],"stop-color":z,"stop-opacity":w}).add(k);k.stops.push(a)}));
c.setAttribute(b,"url("+d.url+"#"+a+")")}},attr:function(a,b){var c,d,e=this.element,f,g=this,h;"string"===typeof a&&b!==C&&(c=a,a={},a[c]=b);if("string"===typeof a)g=(this[a+"Getter"]||this._defaultGetter).call(this,a,e);else{for(c in a)d=a[c],h=!1,this.symbolName&&/^(x|y|width|height|r|start|end|innerR|anchorX|anchorY)/.test(c)&&(f||(this.symbolAttr(a),f=!0),h=!0),!this.rotation||"x"!==c&&"y"!==c||(this.doTransform=!0),h||(this[c+"Setter"]||this._defaultSetter).call(this,d,c,e),this.shadows&&/^(width|height|visibility|x|y|d|transform|cx|cy|r)$/.test(c)&&
this.updateShadows(c,d);this.doTransform&&(this.updateTransform(),this.doTransform=!1)}return g},updateShadows:function(a,b){for(var c=this.shadows,d=c.length;d--;)c[d].setAttribute(a,"height"===a?x(b-(c[d].cutHeight||0),0):"d"===a?this.d:b)},addClass:function(a){var b=this.element,c=m(b,"class")||"";-1===c.indexOf(a)&&m(b,"class",c+" "+a);return this},symbolAttr:function(a){var b=this;t("x y r start end width height innerR anchorX anchorY".split(" "),function(c){b[c]=l(a[c],b[c])});b.attr({d:b.renderer.symbols[b.symbolName](b.x,
b.y,b.width,b.height,b)})},clip:function(a){return this.attr("clip-path",a?"url("+this.renderer.url+"#"+a.id+")":"none")},crisp:function(a){var b,c={},d,e=a.strokeWidth||this.strokeWidth||0;d=B(e)%2/2;a.x=R(a.x||this.x||0)+d;a.y=R(a.y||this.y||0)+d;a.width=R((a.width||this.width||0)-2*d);a.height=R((a.height||this.height||0)-2*d);a.strokeWidth=e;for(b in a)this[b]!==a[b]&&(this[b]=c[b]=a[b]);return c},css:function(a){var b=this.styles,c={},d=this.element,e,f,g="";e=!b;a&&a.color&&(a.fill=a.color);
if(b)for(f in a)a[f]!==b[f]&&(c[f]=a[f],e=!0);if(e){e=this.textWidth=a&&a.width&&"text"===d.nodeName.toLowerCase()&&s(a.width);b&&(a=u(b,c));this.styles=a;e&&(Z||!Q&&this.renderer.forExport)&&delete a.width;if(ha&&!Q)P(this.element,a);else{b=function(a,b){return"-"+b.toLowerCase()};for(f in a)g+=f.replace(/([A-Z])/g,b)+":"+a[f]+";";m(d,"style",g)}e&&this.added&&this.renderer.buildText(this)}return this},on:function(a,b){this.element["on"+a]=b;return this},setRadialReference:function(a){this.element.radialReference=
a;return this},translate:function(a,b){return this.attr({translateX:a,translateY:b})},invert:function(){this.inverted=!0;this.updateTransform();return this},updateTransform:function(){var a=this.translateX||0,b=this.translateY||0,c=this.scaleX,d=this.scaleY,e=this.inverted,f=this.rotation,g=this.element;e&&(a+=this.attr("width"),b+=this.attr("height"));a=["translate("+a+","+b+")"];e?a.push("rotate(90) scale(-1,1)"):f&&a.push("rotate("+f+" "+(g.getAttribute("x")||0)+" "+(g.getAttribute("y")||0)+")");
(p(c)||p(d))&&a.push("scale("+l(c,1)+" "+l(d,1)+")");a.length&&g.setAttribute("transform",a.join(" "))},toFront:function(){var a=this.element;a.parentNode.appendChild(a);return this},align:function(a,b,c){var d,e,f,g,h={};e=this.renderer;f=e.alignedObjects;if(a){if(this.alignOptions=a,this.alignByTranslate=b,!c||W(c))this.alignTo=d=c||"renderer",q(f,this),f.push(this),c=null}else a=this.alignOptions,b=this.alignByTranslate,d=this.alignTo;c=l(c,e[d],e);d=a.align;e=a.verticalAlign;f=(c.x||0)+(a.x||
0);g=(c.y||0)+(a.y||0);if("right"===d||"center"===d)f+=(c.width-(a.width||0))/{right:1,center:2}[d];h[b?"translateX":"x"]=B(f);if("bottom"===e||"middle"===e)g+=(c.height-(a.height||0))/({bottom:1,middle:2}[e]||1);h[b?"translateY":"y"]=B(g);this[this.placed?"animate":"attr"](h);this.placed=!0;this.alignAttr=h;return this},getBBox:function(){var a=this.bBox,b=this.renderer,c,d,e=this.rotation;c=this.element;var f=this.styles,g=e*ab;d=this.textStr;var h;if(""===d||nb.test(d))h="num."+d.toString().length+
(f?"|"+f.fontSize+"|"+f.fontFamily:"");h&&(a=b.cache[h]);if(!a){if("http://www.w3.org/2000/svg"===c.namespaceURI||b.forExport){try{a=c.getBBox?u({},c.getBBox()):{width:c.offsetWidth,height:c.offsetHeight}}catch(k){}if(!a||0>a.width)a={width:0,height:0}}else a=this.htmlGetBBox();b.isSVG&&(c=a.width,d=a.height,ha&&f&&"11px"===f.fontSize&&"16.9"===d.toPrecision(3)&&(a.height=d=14),e&&(a.width=X(d*za(g))+X(c*oa(g)),a.height=X(d*oa(g))+X(c*za(g))));this.bBox=a;h&&(b.cache[h]=a)}return a},show:function(a){a&&
"http://www.w3.org/2000/svg"===this.element.namespaceURI?this.element.removeAttribute("visibility"):this.attr({visibility:a?"inherit":"visible"});return this},hide:function(){return this.attr({visibility:"hidden"})},fadeOut:function(a){var b=this;b.animate({opacity:0},{duration:a||150,complete:function(){b.attr({y:-9999})}})},add:function(a){var b=this.renderer,c=a||b,d=c.element||b.box,e=this.element,f=this.zIndex,g,h;a&&(this.parentGroup=a);this.parentInverted=a&&a.inverted;void 0!==this.textStr&&
b.buildText(this);f&&(c.handleZ=!0,f=s(f));if(c.handleZ)for(a=d.childNodes,g=0;g<a.length;g++)if(b=a[g],c=m(b,"zIndex"),b!==e&&(s(c)>f||!p(f)&&p(c))){d.insertBefore(e,b);h=!0;break}h||d.appendChild(e);this.added=!0;if(this.onAdd)this.onAdd();return this},safeRemoveChild:function(a){var b=a.parentNode;b&&b.removeChild(a)},destroy:function(){var a=this,b=a.element||{},c=a.shadows,d=a.renderer.isSVG&&"SPAN"===b.nodeName&&a.parentGroup,e,f;b.onclick=b.onmouseout=b.onmouseover=b.onmousemove=b.point=null;
Ia(a);a.clipPath&&(a.clipPath=a.clipPath.destroy());if(a.stops){for(f=0;f<a.stops.length;f++)a.stops[f]=a.stops[f].destroy();a.stops=null}a.safeRemoveChild(b);for(c&&t(c,function(b){a.safeRemoveChild(b)});d&&d.div&&0===d.div.childNodes.length;)b=d.parentGroup,a.safeRemoveChild(d.div),delete d.div,d=b;a.alignTo&&q(a.renderer.alignedObjects,a);for(e in a)delete a[e];return null},shadow:function(a,b,c){var d=[],e,f,g=this.element,h,k,v,z;if(a){k=l(a.width,3);v=(a.opacity||.15)/k;z=this.parentInverted?
"(-1,-1)":"("+l(a.offsetX,1)+", "+l(a.offsetY,1)+")";for(e=1;e<=k;e++)f=g.cloneNode(0),h=2*k+1-2*e,m(f,{isShadow:"true",stroke:a.color||"black","stroke-opacity":v*e,"stroke-width":h,transform:"translate"+z,fill:"none"}),c&&(m(f,"height",x(m(f,"height")-h,0)),f.cutHeight=h),b?b.element.appendChild(f):g.parentNode.insertBefore(f,g),d.push(f);this.shadows=d}return this},xGetter:function(a){"circle"===this.element.nodeName&&(a={x:"cx",y:"cy"}[a]||a);return this._defaultGetter(a)},_defaultGetter:function(a){a=
l(this[a],this.element?this.element.getAttribute(a):null,0);/^[\-0-9\.]+$/.test(a)&&(a=parseFloat(a));return a},dSetter:function(a,b,c){a&&a.join&&(a=a.join(" "));/(NaN| {2}|^$)/.test(a)&&(a="M 0 0");c.setAttribute(b,a);this[b]=a},dashstyleSetter:function(a){var b;if(a=a&&a.toLowerCase()){a=a.replace("shortdashdotdot","3,1,1,1,1,1,").replace("shortdashdot","3,1,1,1").replace("shortdot","1,1,").replace("shortdash","3,1,").replace("longdash","8,3,").replace(/dot/g,"1,3,").replace("dash","4,3,").replace(/,$/,
"").split(",");for(b=a.length;b--;)a[b]=s(a[b])*this["stroke-width"];a=a.join(",").replace("NaN","none");this.element.setAttribute("stroke-dasharray",a)}},alignSetter:function(a){this.element.setAttribute("text-anchor",{left:"start",center:"middle",right:"end"}[a])},opacitySetter:function(a,b,c){this[b]=a;c.setAttribute(b,a)},titleSetter:function(a){var b=this.element.getElementsByTagName("title")[0];b||(b=D.createElementNS("http://www.w3.org/2000/svg","title"),this.element.appendChild(b));b.textContent=
l(a,"").replace(/<[^>]*>/g,"")},textSetter:function(a){a!==this.textStr&&(delete this.bBox,this.textStr=a,this.added&&this.renderer.buildText(this))},fillSetter:function(a,b,c){"string"===typeof a?c.setAttribute(b,a):a&&this.colorGradient(a,b,c)},zIndexSetter:function(a,b,c){c.setAttribute(b,a);this[b]=a},_defaultSetter:function(a,b,c){c.setAttribute(b,a)}};I.prototype.yGetter=I.prototype.xGetter;I.prototype.translateXSetter=I.prototype.translateYSetter=I.prototype.rotationSetter=I.prototype.verticalAlignSetter=
I.prototype.scaleXSetter=I.prototype.scaleYSetter=function(a,b){this[b]=a;this.doTransform=!0};I.prototype["stroke-widthSetter"]=I.prototype.strokeSetter=function(a,b,c){this[b]=a;this.stroke&&this["stroke-width"]?(this.strokeWidth=this["stroke-width"],I.prototype.fillSetter.call(this,this.stroke,"stroke",c),c.setAttribute("stroke-width",this["stroke-width"]),this.hasStroke=!0):"stroke-width"===b&&0===a&&this.hasStroke&&(c.removeAttribute("stroke"),this.hasStroke=!1)};var ra=function(){this.init.apply(this,
arguments)};ra.prototype={Element:I,init:function(a,b,c,d,e){var f=location,g;d=this.createElement("svg").attr({version:"1.1"}).css(this.getStyle(d));g=d.element;a.appendChild(g);-1===a.innerHTML.indexOf("xmlns")&&m(g,"xmlns","http://www.w3.org/2000/svg");this.isSVG=!0;this.box=g;this.boxWrapper=d;this.alignedObjects=[];this.url=(Aa||lb)&&D.getElementsByTagName("base").length?f.href.replace(/#.*?$/,"").replace(/([\('\)])/g,"\\$1").replace(/ /g,"%20"):"";this.createElement("desc").add().element.appendChild(D.createTextNode("Created with Highcharts 4.0.4 /Highstock 2.0.4"));
this.defs=this.createElement("defs").add();this.forExport=e;this.gradients={};this.cache={};this.setSize(b,c,!1);var h;Aa&&a.getBoundingClientRect&&(this.subPixelFix=b=function(){P(a,{left:0,top:0});h=a.getBoundingClientRect();P(a,{left:ja(h.left)-h.left+"px",top:ja(h.top)-h.top+"px"})},b(),L(H,"resize",b))},getStyle:function(a){return this.style=u({fontFamily:'"Lucida Grande", "Lucida Sans Unicode", Arial, Helvetica, sans-serif',fontSize:"12px"},a)},isHidden:function(){return!this.boxWrapper.getBBox().width},
destroy:function(){var a=this.defs;this.box=null;this.boxWrapper=this.boxWrapper.destroy();va(this.gradients||{});this.gradients=null;a&&(this.defs=a.destroy());this.subPixelFix&&T(H,"resize",this.subPixelFix);return this.alignedObjects=null},createElement:function(a){var b=new this.Element;b.init(this,a);return b},draw:function(){},buildText:function(a){for(var b=a.element,c=this,d=c.forExport,e=l(a.textStr,"").toString(),f=-1!==e.indexOf("<"),g=b.childNodes,h,k,v=m(b,"x"),z=a.styles,w=a.textWidth,
E=z&&z.lineHeight,r=z&&z.HcTextStroke,p=g.length,n=function(a){return E?s(E):c.fontMetrics(/(px|em)$/.test(a&&a.style.fontSize)?a.style.fontSize:z&&z.fontSize||c.style.fontSize||12,a).h};p--;)b.removeChild(g[p]);f||r||-1!==e.indexOf(" ")?(h=/<.*style="([^"]+)".*>/,k=/<.*href="(http[^"]+)".*>/,w&&!a.added&&this.box.appendChild(b),e=f?e.replace(/<(b|strong)>/g,'<span style="font-weight:bold">').replace(/<(i|em)>/g,'<span style="font-style:italic">').replace(/<a/g,"<span").replace(/<\/(b|strong|i|em|a)>/g,
"</span>").split(/<br.*?>/g):[e],""===e[e.length-1]&&e.pop(),t(e,function(e,f){var g,r=0;e=e.replace(/<span/g,"|||<span").replace(/<\/span>/g,"</span>|||");g=e.split("|||");t(g,function(e){if(""!==e||1===g.length){var E={},l=D.createElementNS("http://www.w3.org/2000/svg","tspan"),p;h.test(e)&&(p=e.match(h)[1].replace(/(;| |^)color([ :])/,"$1fill$2"),m(l,"style",p));k.test(e)&&!d&&(m(l,"onclick",'location.href="'+e.match(k)[1]+'"'),P(l,{cursor:"pointer"}));e=(e.replace(/<(.|\n)*?>/g,"")||" ").replace(/&lt;/g,
"<").replace(/&gt;/g,">");if(" "!==e){l.appendChild(D.createTextNode(e));r?E.dx=0:f&&null!==v&&(E.x=v);m(l,E);b.appendChild(l);!r&&f&&(!Q&&d&&P(l,{display:"block"}),m(l,"dy",n(l)));if(w){e=e.replace(/([^\^])-/g,"$1- ").split(" ");for(var E=1<g.length||1<e.length&&"nowrap"!==z.whiteSpace,La,q,t=z.HcHeight,s=[],u=n(l),ib=1;E&&(e.length||s.length);)delete a.bBox,La=a.getBBox(),q=La.width,!Q&&c.forExport&&(q=c.measureSpanWidth(l.firstChild.data,a.styles)),(La=q>w)&&1!==e.length?(l.removeChild(l.firstChild),
s.unshift(e.pop())):(e=s,s=[],e.length&&(ib++,t&&ib*u>t?(e=["..."],a.attr("title",a.textStr)):(l=D.createElementNS("http://www.w3.org/2000/svg","tspan"),m(l,{dy:u,x:v}),p&&m(l,"style",p),b.appendChild(l))),q>w&&(w=q)),e.length&&l.appendChild(D.createTextNode(e.join(" ").replace(/- /g,"-")))}r++}}})})):b.appendChild(D.createTextNode(e))},button:function(a,b,c,d,e,f,g,h,k){var v=this.label(a,b,c,k,null,null,null,null,"button"),z=0,w,l,r,p,m,n;a={x1:0,y1:0,x2:0,y2:1};e=A({"stroke-width":1,stroke:"#CCCCCC",
fill:{linearGradient:a,stops:[[0,"#FEFEFE"],[1,"#F6F6F6"]]},r:2,padding:5,style:{color:"black"}},e);r=e.style;delete e.style;f=A(e,{stroke:"#68A",fill:{linearGradient:a,stops:[[0,"#FFF"],[1,"#ACF"]]}},f);p=f.style;delete f.style;g=A(e,{stroke:"#68A",fill:{linearGradient:a,stops:[[0,"#9BD"],[1,"#CDF"]]}},g);m=g.style;delete g.style;h=A(e,{style:{color:"#CCC"}},h);n=h.style;delete h.style;L(v.element,ha?"mouseover":"mouseenter",function(){3!==z&&v.attr(f).css(p)});L(v.element,ha?"mouseout":"mouseleave",
function(){3!==z&&(w=[e,f,g][z],l=[r,p,m][z],v.attr(w).css(l))});v.setState=function(a){(v.state=z=a)?2===a?v.attr(g).css(m):3===a&&v.attr(h).css(n):v.attr(e).css(r)};return v.on("click",function(){3!==z&&d.call(v)}).attr(e).css(u({cursor:"default"},r))},crispLine:function(a,b){a[1]===a[4]&&(a[1]=a[4]=B(a[1])-b%2/2);a[2]===a[5]&&(a[2]=a[5]=B(a[2])+b%2/2);return a},path:function(a){var b={fill:"none"};aa(a)?b.d=a:y(a)&&u(b,a);return this.createElement("path").attr(b)},circle:function(a,b,c){a=y(a)?
a:{x:a,y:b,r:c};b=this.createElement("circle");b.xSetter=function(a){this.element.setAttribute("cx",a)};b.ySetter=function(a){this.element.setAttribute("cy",a)};return b.attr(a)},arc:function(a,b,c,d,e,f){y(a)&&(b=a.y,c=a.r,d=a.innerR,e=a.start,f=a.end,a=a.x);a=this.symbol("arc",a||0,b||0,c||0,c||0,{innerR:d||0,start:e||0,end:f||0});a.r=c;return a},rect:function(a,b,c,d,e,f){e=y(a)?a.r:e;var g=this.createElement("rect");a=y(a)?a:a===C?{}:{x:a,y:b,width:x(c,0),height:x(d,0)};f!==C&&(a.strokeWidth=
f,a=g.crisp(a));e&&(a.r=e);g.rSetter=function(a){m(this.element,{rx:a,ry:a})};return g.attr(a)},setSize:function(a,b,c){var d=this.alignedObjects,e=d.length;this.width=a;this.height=b;for(this.boxWrapper[l(c,!0)?"animate":"attr"]({width:a,height:b});e--;)d[e].align()},g:function(a){var b=this.createElement("g");return p(a)?b.attr({"class":"highcharts-"+a}):b},image:function(a,b,c,d,e){var f={preserveAspectRatio:"none"};1<arguments.length&&u(f,{x:b,y:c,width:d,height:e});f=this.createElement("image").attr(f);
f.element.setAttributeNS?f.element.setAttributeNS("http://www.w3.org/1999/xlink","href",a):f.element.setAttribute("hc-svg-href",a);return f},symbol:function(a,b,c,d,e,f){var g,h=this.symbols[a],h=h&&h(B(b),B(c),d,e,f),k=/^url\((.*?)\)$/,v,z;h?(g=this.path(h),u(g,{symbolName:a,x:b,y:c,width:d,height:e}),f&&u(g,f)):k.test(a)&&(z=function(a,b){a.element&&(a.attr({width:b[0],height:b[1]}),a.alignByTranslate||a.translate(B((d-b[0])/2),B((e-b[1])/2)))},v=a.match(k)[1],a=cb[v]||f&&f.width&&f.height&&[f.width,
f.height],g=this.image(v).attr({x:b,y:c}),g.isImg=!0,a?z(g,a):(g.attr({width:0,height:0}),ma("img",{onload:function(){z(g,cb[v]=[this.width,this.height])},src:v})));return g},symbols:{circle:function(a,b,c,d){var e=.166*c;return["M",a+c/2,b,"C",a+c+e,b,a+c+e,b+d,a+c/2,b+d,"C",a-e,b+d,a-e,b,a+c/2,b,"Z"]},square:function(a,b,c,d){return["M",a,b,"L",a+c,b,a+c,b+d,a,b+d,"Z"]},triangle:function(a,b,c,d){return["M",a+c/2,b,"L",a+c,b+d,a,b+d,"Z"]},"triangle-down":function(a,b,c,d){return["M",a,b,"L",a+c,
b,a+c/2,b+d,"Z"]},diamond:function(a,b,c,d){return["M",a+c/2,b,"L",a+c,b+d/2,a+c/2,b+d,a,b+d/2,"Z"]},arc:function(a,b,c,d,e){var f=e.start;c=e.r||c||d;var g=e.end-.001;d=e.innerR;var h=e.open,k=oa(f),v=za(f),z=oa(g),g=za(g);e=e.end-f<$a?0:1;return["M",a+c*k,b+c*v,"A",c,c,0,e,1,a+c*z,b+c*g,h?"M":"L",a+d*z,b+d*g,"A",d,d,0,e,0,a+d*k,b+d*v,h?"":"Z"]},callout:function(a,b,c,d,e){var f=U(e&&e.r||0,c,d),g=f+6,h=e&&e.anchorX,k=e&&e.anchorY;e=B(e.strokeWidth||0)%2/2;a+=e;b+=e;e=["M",a+f,b,"L",a+c-f,b,"C",
a+c,b,a+c,b,a+c,b+f,"L",a+c,b+d-f,"C",a+c,b+d,a+c,b+d,a+c-f,b+d,"L",a+f,b+d,"C",a,b+d,a,b+d,a,b+d-f,"L",a,b+f,"C",a,b,a,b,a+f,b];h&&h>c&&k>b+g&&k<b+d-g?e.splice(13,3,"L",a+c,k-6,a+c+6,k,a+c,k+6,a+c,b+d-f):h&&0>h&&k>b+g&&k<b+d-g?e.splice(33,3,"L",a,k+6,a-6,k,a,k-6,a,b+f):k&&k>d&&h>a+g&&h<a+c-g?e.splice(23,3,"L",h+6,b+d,h,b+d+6,h-6,b+d,a+f,b+d):k&&0>k&&h>a+g&&h<a+c-g&&e.splice(3,3,"L",h-6,b,h,b-6,h+6,b,c-f,b);return e}},clipRect:function(a,b,c,d){var e="highcharts-"+Ga++,f=this.createElement("clipPath").attr({id:e}).add(this.defs);
a=this.rect(a,b,c,d,0).add(f);a.id=e;a.clipPath=f;return a},text:function(a,b,c,d){var e=Z||!Q&&this.forExport,f={};if(d&&!this.forExport)return this.html(a,b,c);f.x=Math.round(b||0);c&&(f.y=Math.round(c));if(a||0===a)f.text=a;a=this.createElement("text").attr(f);e&&a.css({position:"absolute"});d||(a.xSetter=function(a,b,c){var d=c.getElementsByTagName("tspan"),e,f=c.getAttribute(b),l;for(l=0;l<d.length;l++)e=d[l],e.getAttribute(b)===f&&e.setAttribute(b,a);c.setAttribute(b,a)});return a},fontMetrics:function(a,
b){a=a||this.style.fontSize;b&&H.getComputedStyle&&(b=b.element||b,a=H.getComputedStyle(b,"").fontSize);a=/px/.test(a)?s(a):/em/.test(a)?12*parseFloat(a):12;var c=24>a?a+4:B(1.2*a),d=B(.8*c);return{h:c,b:d,f:a}},label:function(a,b,c,d,e,f,g,h,k){function v(){var a,b;a=m.element.style;q=(void 0===ka||void 0===y||r.styles.textAlign)&&m.textStr&&m.getBBox();r.width=(ka||q.width||0)+2*J+x;r.height=(y||q.height||0)+2*J;ca=J+E.fontMetrics(a&&a.fontSize,m).b;F&&(n||(a=B(-s*J),b=h?-ca:0,r.box=n=d?E.symbol(d,
a,b,r.width,r.height,K):E.rect(a,b,r.width,r.height,0,K["stroke-width"]),n.attr("fill","none").add(r)),n.isImg||n.attr(u({width:B(r.width),height:B(r.height)},K)),K=null)}function l(){var a=r.styles,a=a&&a.textAlign,b=x+J*(1-s),c;c=h?0:ca;p(ka)&&q&&("center"===a||"right"===a)&&(b+={center:.5,right:1}[a]*(ka-q.width));if(b!==m.x||c!==m.y)m.attr("x",b),c!==C&&m.attr("y",c);m.x=b;m.y=c}function w(a,b){n?n.attr(a,b):K[a]=b}var E=this,r=E.g(k),m=E.text("",0,0,g).attr({zIndex:1}),n,q,s=0,J=3,x=0,ka,y,D,
Ma,hb=0,K={},ca,F;r.onAdd=function(){m.add(r);r.attr({text:a||0===a?a:"",x:b,y:c});n&&p(e)&&r.attr({anchorX:e,anchorY:f})};r.widthSetter=function(a){ka=a};r.heightSetter=function(a){y=a};r.paddingSetter=function(a){p(a)&&a!==J&&(J=a,l())};r.paddingLeftSetter=function(a){p(a)&&a!==x&&(x=a,l())};r.alignSetter=function(a){s={left:0,center:.5,right:1}[a]};r.textSetter=function(a){a!==C&&m.textSetter(a);v();l()};r["stroke-widthSetter"]=function(a,b){a&&(F=!0);hb=a%2/2;w(b,a)};r.strokeSetter=r.fillSetter=
r.rSetter=function(a,b){"fill"===b&&a&&(F=!0);w(b,a)};r.anchorXSetter=function(a,b){e=a;w(b,a+hb-D)};r.anchorYSetter=function(a,b){f=a;w(b,a-Ma)};r.xSetter=function(a){r.x=a;s&&(a-=s*((ka||q.width)+J));D=B(a);r.attr("translateX",D)};r.ySetter=function(a){Ma=r.y=B(a);r.attr("translateY",Ma)};var H=r.css;return u(r,{css:function(a){if(a){var b={};a=A(a);t(r.textProps,function(c){a[c]!==C&&(b[c]=a[c],delete a[c])});m.css(b)}return H.call(r,a)},getBBox:function(){return{width:q.width+2*J,height:q.height+
2*J,x:q.x-J,y:q.y-J}},shadow:function(a){n&&n.shadow(a);return r},destroy:function(){T(r.element,"mouseenter");T(r.element,"mouseleave");m&&(m=m.destroy());n&&(n=n.destroy());I.prototype.destroy.call(r);r=E=v=l=w=null}})}};ia.prototype={addLabel:function(){var a=this.axis,b=a.options,c=a.chart,d=a.horiz,e=a.categories,f=a.names,g=this.pos,h=b.labels,k=h.rotation,v=a.tickPositions,d=d&&e&&!h.step&&!h.staggerLines&&!h.rotation&&c.plotWidth/v.length||!d&&(c.margin[3]||.33*c.chartWidth),z=g===v[0],w=
g===v[v.length-1],E,f=e?l(e[g],f[g],g):g,e=this.label,r=v.info;a.isDatetimeAxis&&r&&(E=b.dateTimeLabelFormats[r.higherRanks[g]||r.unitName]);this.isFirst=z;this.isLast=w;b=a.labelFormatter.call({axis:a,chart:c,isFirst:z,isLast:w,dateTimeLabelFormat:E,value:a.isLog?Y(n(f)):f});g=d&&{width:x(1,B(d-2*(h.padding||10)))+"px"};p(e)?e&&e.attr({text:b}).css(g):(E={align:a.labelAlign},N(k)&&(E.rotation=k),d&&h.ellipsis&&(g.HcHeight=a.len/v.length),this.label=e=p(b)&&h.enabled?c.renderer.text(b,0,0,h.useHTML).attr(E).css(u(g,
h.style)).add(a.labelGroup):null,a.tickBaseline=c.renderer.fontMetrics(h.style.fontSize,e).b,k&&2===a.side&&(a.tickBaseline*=oa(k*ab)));this.yOffset=e?l(h.y,a.tickBaseline+(2===a.side?8:-(e.getBBox().height/2))):0},getLabelSize:function(){var a=this.label,b=this.axis;return a?a.getBBox()[b.horiz?"height":"width"]:0},getLabelSides:function(){var a=this.label.getBBox(),b=this.axis,c=b.horiz,d=b.options.labels,a=c?a.width:a.height,b=c?d.x-a*{left:0,center:.5,right:1}[b.labelAlign]:0;return[b,c?a+b:a]},
handleOverflow:function(a,b){var c=!0,d=this.axis,e=this.isFirst,f=this.isLast,g=d.horiz?b.x:b.y,h=d.reversed,k=d.tickPositions,v=this.getLabelSides(),l=v[0],v=v[1],w,p,r,m=this.label.line;w=m||0;p=d.labelEdge;r=d.justifyLabels&&(e||f);p[w]===C||g+l>p[w]?p[w]=g+v:r||(c=!1);if(r){w=(p=d.justifyToPlot)?d.pos:0;p=p?w+d.len:d.chart.chartWidth;do a+=e?1:-1,r=d.ticks[k[a]];while(k[a]&&(!r||!r.label||r.label.line!==m));d=r&&r.label.xy&&r.label.xy.x+r.getLabelSides()[e?0:1];e&&!h||f&&h?g+l<w&&(g=w-l,r&&g+
v>d&&(c=!1)):g+v>p&&(g=p-v,r&&g+l<d&&(c=!1));b.x=g}return c},getPosition:function(a,b,c,d){var e=this.axis,f=e.chart,g=d&&f.oldChartHeight||f.chartHeight;return{x:a?e.translate(b+c,null,null,d)+e.transB:e.left+e.offset+(e.opposite?(d&&f.oldChartWidth||f.chartWidth)-e.right-e.left:0),y:a?g-e.bottom+e.offset-(e.opposite?e.height:0):g-e.translate(b+c,null,null,d)-e.transB}},getLabelPosition:function(a,b,c,d,e,f,g,h){var k=this.axis,v=k.transA,l=k.reversed,w=k.staggerLines;a=a+e.x-(f&&d?f*v*(l?-1:1):
0);b=b+this.yOffset-(f&&!d?f*v*(l?1:-1):0);w&&(c.line=g/(h||1)%w,b+=k.labelOffset/w*c.line);return{x:a,y:b}},getMarkPath:function(a,b,c,d,e,f){return f.crispLine(["M",a,b,"L",a+(e?0:-c),b+(e?c:0)],d)},render:function(a,b,c){var d=this.axis,e=d.options,f=d.chart.renderer,g=d.horiz,h=this.type,k=this.label,v=this.pos,z=e.labels,w=this.gridLine,p=h?h+"Grid":"grid",r=h?h+"Tick":"tick",m=e[p+"LineWidth"],n=e[p+"LineColor"],q=e[p+"LineDashStyle"],t=e[r+"Length"],p=e[r+"Width"]||0,s=e[r+"Color"],u=e[r+"Position"],
r=this.mark,x=z.step,A=!0,B=d.tickmarkOffset,y=this.getPosition(g,v,B,b),D=y.x,y=y.y,K=g&&D===d.pos+d.len||!g&&y===d.pos?-1:1;c=l(c,1);this.isActive=!0;if(m&&(v=d.getPlotLinePath(v+B,m*K,b,!0),w===C&&(w={stroke:n,"stroke-width":m},q&&(w.dashstyle=q),h||(w.zIndex=1),b&&(w.opacity=0),this.gridLine=w=m?f.path(v).attr(w).add(d.gridGroup):null),!b&&w&&v))w[this.isNew?"attr":"animate"]({d:v,opacity:c});p&&t&&("inside"===u&&(t=-t),d.opposite&&(t=-t),h=this.getMarkPath(D,y,t,p*K,g,f),r?r.animate({d:h,opacity:c}):
this.mark=f.path(h).attr({stroke:s,"stroke-width":p,opacity:c}).add(d.axisGroup));k&&!isNaN(D)&&(k.xy=y=this.getLabelPosition(D,y,k,g,z,B,a,x),this.isFirst&&!this.isLast&&!l(e.showFirstLabel,1)||this.isLast&&!this.isFirst&&!l(e.showLastLabel,1)?A=!1:d.isRadial||z.step||z.rotation||b||0===c||(A=this.handleOverflow(a,y)),x&&a%x&&(A=!1),A&&!isNaN(y.y)?(y.opacity=c,k[this.isNew?"attr":"animate"](y),this.isNew=!1):k.attr("y",-9999))},destroy:function(){va(this,this.axis)}};ya.prototype={defaultOptions:{dateTimeLabelFormats:{millisecond:"%H:%M:%S.%L",
second:"%H:%M:%S",minute:"%H:%M",hour:"%H:%M",day:"%e. %b",week:"%e. %b",month:"%b '%y",year:"%Y"},endOnTick:!1,gridLineColor:"#C0C0C0",labels:Ja,lineColor:"#C0D0E0",lineWidth:1,minPadding:.01,maxPadding:.01,minorGridLineColor:"#E0E0E0",minorGridLineWidth:1,minorTickColor:"#A0A0A0",minorTickLength:2,minorTickPosition:"outside",startOfWeek:1,startOnTick:!1,tickColor:"#C0D0E0",tickLength:10,tickmarkPlacement:"between",tickPixelInterval:100,tickPosition:"outside",tickWidth:1,title:{align:"middle",style:{color:"#707070"}},
type:"linear"},defaultYAxisOptions:{endOnTick:!0,gridLineWidth:1,tickPixelInterval:72,showLastLabel:!0,labels:{x:-8,y:3},lineWidth:0,maxPadding:.05,minPadding:.05,startOnTick:!0,tickWidth:0,title:{rotation:270,text:"Values"},stackLabels:{enabled:!1,formatter:function(){return $(this.total,-1)},style:Ja.style}},defaultLeftAxisOptions:{labels:{x:-15,y:null},title:{rotation:270}},defaultRightAxisOptions:{labels:{x:15,y:null},title:{rotation:90}},defaultBottomAxisOptions:{labels:{x:0,y:null},title:{rotation:0}},
defaultTopAxisOptions:{labels:{x:0,y:-15},title:{rotation:0}},init:function(a,b){var c=b.isX;this.horiz=a.inverted?!c:c;this.coll=(this.isXAxis=c)?"xAxis":"yAxis";this.opposite=b.opposite;this.side=b.side||(this.horiz?this.opposite?0:2:this.opposite?1:3);this.setOptions(b);var d=this.options,e=d.type;this.labelFormatter=d.labels.formatter||this.defaultLabelFormatter;this.userOptions=b;this.minPixelPadding=0;this.chart=a;this.reversed=d.reversed;this.zoomEnabled=!1!==d.zoomEnabled;this.categories=
d.categories||"category"===e;this.names=[];this.isLog="logarithmic"===e;this.isDatetimeAxis="datetime"===e;this.isLinked=p(d.linkedTo);this.tickmarkOffset=this.categories&&"between"===d.tickmarkPlacement&&1===l(d.tickInterval,1)?.5:0;this.ticks={};this.labelEdge=[];this.minorTicks={};this.plotLinesAndBands=[];this.alternateBands={};this.len=0;this.minRange=this.userMinRange=d.minRange||d.maxZoom;this.range=d.range;this.offset=d.offset||0;this.stacks={};this.oldStacks={};this.min=this.max=null;this.crosshair=
l(d.crosshair,la(a.options.tooltip.crosshairs)[c?0:1],!1);var f,d=this.options.events;-1===ob(this,a.axes)&&(c&&!this.isColorAxis?a.axes.splice(a.xAxis.length,0,this):a.axes.push(this),a[this.coll].push(this));this.series=this.series||[];a.inverted&&c&&this.reversed===C&&(this.reversed=!0);this.removePlotLine=this.removePlotBand=this.removePlotBandOrLine;for(f in d)L(this,f,d[f]);this.isLog&&(this.val2lin=ea,this.lin2val=n)},setOptions:function(a){this.options=A(this.defaultOptions,this.isXAxis?{}:
this.defaultYAxisOptions,[this.defaultTopAxisOptions,this.defaultRightAxisOptions,this.defaultBottomAxisOptions,this.defaultLeftAxisOptions][this.side],A(F[this.coll],a))},defaultLabelFormatter:function(){var a=this.axis,b=this.value,c=a.categories,d=this.dateTimeLabelFormat,e=F.lang.numericSymbols,f=e&&e.length,g,h=a.options.labels.format,a=a.isLog?b:a.tickInterval;if(h)g=sa(h,this);else if(c)g=b;else if(d)g=ta(d,b);else if(f&&1E3<=a)for(;f--&&g===C;)c=Math.pow(1E3,f+1),a>=c&&null!==e[f]&&(g=$(b/
c,-1)+e[f]);g===C&&(g=1E4<=X(b)?$(b,0):$(b,-1,C,""));return g},getSeriesExtremes:function(){var a=this,b=a.chart;a.hasVisibleSeries=!1;a.dataMin=a.dataMax=a.ignoreMinPadding=a.ignoreMaxPadding=null;a.buildStacks&&a.buildStacks();t(a.series,function(c){if(c.visible||!b.options.chart.ignoreHiddenSeries){var d;d=c.options.threshold;var e;a.hasVisibleSeries=!0;a.isLog&&0>=d&&(d=null);a.isXAxis?(d=c.xData,d.length&&(a.dataMin=U(l(a.dataMin,d[0]),ua(d)),a.dataMax=x(l(a.dataMax,d[0]),na(d)))):(c.getExtremes(),
e=c.dataMax,c=c.dataMin,p(c)&&p(e)&&(a.dataMin=U(l(a.dataMin,c),c),a.dataMax=x(l(a.dataMax,e),e)),p(d)&&(a.dataMin>=d?(a.dataMin=d,a.ignoreMinPadding=!0):a.dataMax<d&&(a.dataMax=d,a.ignoreMaxPadding=!0)))}})},translate:function(a,b,c,d,e,f){var g=1,h=0,k=d?this.oldTransA:this.transA;d=d?this.oldMin:this.min;var v=this.minPixelPadding;e=(this.options.ordinal||this.isLog&&e)&&this.lin2val;k||(k=this.transA);c&&(g*=-1,h=this.len);this.reversed&&(g*=-1,h-=g*(this.sector||this.len));b?(a=a*g+h-v,a=a/k+
d,e&&(a=this.lin2val(a))):(e&&(a=this.val2lin(a)),"between"===f&&(f=.5),a=g*(a-d)*k+h+g*v+(N(f)?k*f*this.pointRange:0));return a},toPixels:function(a,b){return this.translate(a,!1,!this.horiz,null,!0)+(b?0:this.pos)},toValue:function(a,b){return this.translate(a-(b?0:this.pos),!0,!this.horiz,null,!0)},getPlotLinePath:function(a,b,c,d,e){var f=this.chart,g=this.left,h=this.top,k,v,p=c&&f.oldChartHeight||f.chartHeight,w=c&&f.oldChartWidth||f.chartWidth,m;k=this.transB;e=l(e,this.translate(a,null,null,
c));a=c=B(e+k);k=v=B(p-e-k);if(isNaN(e))m=!0;else if(this.horiz){if(k=h,v=p-this.bottom,a<g||a>g+this.width)m=!0}else if(a=g,c=w-this.right,k<h||k>h+this.height)m=!0;return m&&!d?null:f.renderer.crispLine(["M",a,k,"L",c,v],b||1)},getLinearTickPositions:function(a,b,c){var d,e=Y(R(b/a)*a),f=Y(ja(c/a)*a),g=[];if(b===c&&N(b))return[b];for(b=e;b<=f;){g.push(b);b=Y(b+a);if(b===d)break;d=b}return g},getMinorTickPositions:function(){var a=this.options,b=this.tickPositions,c=this.minorTickInterval,d=[],e;
if(this.isLog)for(e=b.length,a=1;a<e;a++)d=d.concat(this.getLogTickPositions(c,b[a-1],b[a],!0));else if(this.isDatetimeAxis&&"auto"===a.minorTickInterval)d=d.concat(this.getTimeTicks(this.normalizeTimeTickInterval(c),this.min,this.max,a.startOfWeek)),d[0]<this.min&&d.shift();else for(b=this.min+(b[0]-this.min)%c;b<=this.max;b+=c)d.push(b);return d},adjustForMinRange:function(){var a=this.options,b=this.min,c=this.max,d,e=this.dataMax-this.dataMin>=this.minRange,f,g,h,k,v;this.isXAxis&&this.minRange===
C&&!this.isLog&&(p(a.min)||p(a.max)?this.minRange=null:(t(this.series,function(a){k=a.xData;for(g=v=a.xIncrement?1:k.length-1;0<g;g--)if(h=k[g]-k[g-1],f===C||h<f)f=h}),this.minRange=U(5*f,this.dataMax-this.dataMin)));if(c-b<this.minRange){var z=this.minRange;d=(z-c+b)/2;d=[b-d,l(a.min,b-d)];e&&(d[2]=this.dataMin);b=na(d);c=[b+z,l(a.max,b+z)];e&&(c[2]=this.dataMax);c=ua(c);c-b<z&&(d[0]=c-z,d[1]=l(a.min,c-z),b=na(d))}this.min=b;this.max=c},setAxisTranslation:function(a){var b=this,c=b.max-b.min,d=b.axisPointRange||
0,e,f=0,g=0,h=b.linkedParent,k=!!b.categories,v=b.transA;if(b.isXAxis||k||d)h?(f=h.minPointOffset,g=h.pointRangePadding):t(b.series,function(a){var h=k?1:b.isXAxis?a.pointRange:b.axisPointRange||0,v=a.options.pointPlacement,l=a.closestPointRange;h>c&&(h=0);d=x(d,h);f=x(f,W(v)?0:h/2);g=x(g,"on"===v?0:h);!a.noSharedTooltip&&p(l)&&(e=p(e)?U(e,l):l)}),h=b.ordinalSlope&&e?b.ordinalSlope/e:1,b.minPointOffset=f*=h,b.pointRangePadding=g*=h,b.pointRange=U(d,c),b.closestPointRange=e;a&&(b.oldTransA=v);b.translationSlope=
b.transA=v=b.len/(c+g||1);b.transB=b.horiz?b.left:b.bottom;b.minPixelPadding=v*f},setTickPositions:function(a){var b=this,c=b.chart,d=b.options,e=d.startOnTick,f=d.endOnTick,g=b.isLog,h=b.isDatetimeAxis,k=b.isXAxis,v=b.isLinked,z=b.options.tickPositioner,w=d.maxPadding,m=d.minPadding,r=d.tickInterval,n=d.minTickInterval,q=d.tickPixelInterval,s,u=b.categories;v?(b.linkedParent=c[b.coll][d.linkedTo],c=b.linkedParent.getExtremes(),b.min=l(c.min,c.dataMin),b.max=l(c.max,c.dataMax),d.type!==b.linkedParent.options.type&&
O(11,1)):(b.min=l(b.userMin,d.min,b.dataMin),b.max=l(b.userMax,d.max,b.dataMax));g&&(!a&&0>=U(b.min,l(b.dataMin,b.min))&&O(10,1),b.min=Y(ea(b.min)),b.max=Y(ea(b.max)));b.range&&p(b.max)&&(b.userMin=b.min=x(b.min,b.max-b.range),b.userMax=b.max,b.range=null);b.beforePadding&&b.beforePadding();b.adjustForMinRange();!(u||b.axisPointRange||b.usePercentage||v)&&p(b.min)&&p(b.max)&&(c=b.max-b.min)&&(p(d.min)||p(b.userMin)||!m||!(0>b.dataMin)&&b.ignoreMinPadding||(b.min-=c*m),p(d.max)||p(b.userMax)||!w||
!(0<b.dataMax)&&b.ignoreMaxPadding||(b.max+=c*w));N(d.floor)&&(b.min=x(b.min,d.floor));N(d.ceiling)&&(b.max=U(b.max,d.ceiling));b.min===b.max||void 0===b.min||void 0===b.max?b.tickInterval=1:v&&!r&&q===b.linkedParent.options.tickPixelInterval?b.tickInterval=b.linkedParent.tickInterval:(b.tickInterval=l(r,u?1:(b.max-b.min)*q/x(b.len,q)),!p(r)&&b.len<q&&!this.isRadial&&!this.isLog&&!u&&e&&f&&(s=!0,b.tickInterval/=4));k&&!a&&t(b.series,function(a){a.processData(b.min!==b.oldMin||b.max!==b.oldMax)});
b.setAxisTranslation(!0);b.beforeSetTickPositions&&b.beforeSetTickPositions();b.postProcessTickInterval&&(b.tickInterval=b.postProcessTickInterval(b.tickInterval));b.pointRange&&(b.tickInterval=x(b.pointRange,b.tickInterval));!r&&b.tickInterval<n&&(b.tickInterval=n);h||g||r||(b.tickInterval=jb(b.tickInterval,null,G.pow(10,R(G.log(b.tickInterval)/G.LN10)),l(d.allowDecimals,!(1<b.tickInterval&&5>b.tickInterval&&1E3<b.max&&9999>b.max))));b.minorTickInterval="auto"===d.minorTickInterval&&b.tickInterval?
b.tickInterval/5:d.minorTickInterval;b.tickPositions=a=d.tickPositions?[].concat(d.tickPositions):z&&z.apply(b,[b.min,b.max]);a||(!b.ordinalPositions&&(b.max-b.min)/b.tickInterval>x(2*b.len,200)&&O(19,!0),a=h?b.getTimeTicks(b.normalizeTimeTickInterval(b.tickInterval,d.units),b.min,b.max,d.startOfWeek,b.ordinalPositions,b.closestPointRange,!0):g?b.getLogTickPositions(b.tickInterval,b.min,b.max):b.getLinearTickPositions(b.tickInterval,b.min,b.max),s&&a.splice(1,a.length-2),b.tickPositions=a);v||(d=
a[0],g=a[a.length-1],h=b.minPointOffset||0,e?b.min=d:b.min-h>d&&a.shift(),f?b.max=g:b.max+h<g&&a.pop(),0===a.length&&p(d)&&a.push((g+d)/2),1===a.length&&(e=1E13<X(b.max)?1:.001,b.min-=e,b.max+=e))},setMaxTicks:function(){var a=this.chart,b=a.maxTicks||{},c=this.tickPositions,d=this._maxTicksKey=[this.coll,this.pos,this.len].join("-");!this.isLinked&&!this.isDatetimeAxis&&c&&c.length>(b[d]||0)&&!1!==this.options.alignTicks&&(b[d]=c.length);a.maxTicks=b},adjustTickAmount:function(){var a=this._maxTicksKey,
b=this.tickPositions,c=this.chart.maxTicks;if(c&&c[a]&&!this.isDatetimeAxis&&!this.categories&&!this.isLinked&&!1!==this.options.alignTicks&&this.min!==C){var d=this.tickAmount,e=b.length;this.tickAmount=a=c[a];if(e<a){for(;b.length<a;)b.push(Y(b[b.length-1]+this.tickInterval));this.transA*=(e-1)/(a-1);this.max=b[b.length-1]}p(d)&&a!==d&&(this.isDirty=!0)}},setScale:function(){var a=this.stacks,b,c,d,e;this.oldMin=this.min;this.oldMax=this.max;this.oldAxisLength=this.len;this.setAxisSize();e=this.len!==
this.oldAxisLength;t(this.series,function(a){if(a.isDirtyData||a.isDirty||a.xAxis.isDirty)d=!0});if(e||d||this.isLinked||this.forceRedraw||this.userMin!==this.oldUserMin||this.userMax!==this.oldUserMax){if(!this.isXAxis)for(b in a)for(c in a[b])a[b][c].total=null,a[b][c].cum=0;this.forceRedraw=!1;this.getSeriesExtremes();this.setTickPositions();this.oldUserMin=this.userMin;this.oldUserMax=this.userMax;this.isDirty||(this.isDirty=e||this.min!==this.oldMin||this.max!==this.oldMax)}else if(!this.isXAxis)for(b in this.oldStacks&&
(a=this.stacks=this.oldStacks),a)for(c in a[b])a[b][c].cum=a[b][c].total;this.setMaxTicks()},setExtremes:function(a,b,c,d,e){var f=this,g=f.chart;c=l(c,!0);e=u(e,{min:a,max:b});M(f,"setExtremes",e,function(){f.userMin=a;f.userMax=b;f.eventArgs=e;f.isDirtyExtremes=!0;c&&g.redraw(d)})},zoom:function(a,b){var c=this.dataMin,d=this.dataMax,e=this.options;this.allowZoomOutside||(p(c)&&a<=U(c,l(e.min,c))&&(a=C),p(d)&&b>=x(d,l(e.max,d))&&(b=C));this.displayBtn=a!==C||b!==C;this.setExtremes(a,b,!1,C,{trigger:"zoom"});
return!0},setAxisSize:function(){var a=this.chart,b=this.options,c=b.offsetLeft||0,d=this.horiz,e=l(b.width,a.plotWidth-c+(b.offsetRight||0)),f=l(b.height,a.plotHeight),g=l(b.top,a.plotTop),b=l(b.left,a.plotLeft+c),c=/%$/;c.test(f)&&(f=parseInt(f,10)/100*a.plotHeight);c.test(g)&&(g=parseInt(g,10)/100*a.plotHeight+a.plotTop);this.left=b;this.top=g;this.width=e;this.height=f;this.bottom=a.chartHeight-f-g;this.right=a.chartWidth-e-b;this.len=x(d?e:f,0);this.pos=d?b:g},getExtremes:function(){var a=this.isLog;
return{min:a?Y(n(this.min)):this.min,max:a?Y(n(this.max)):this.max,dataMin:this.dataMin,dataMax:this.dataMax,userMin:this.userMin,userMax:this.userMax}},getThreshold:function(a){var b=this.isLog,c=b?n(this.min):this.min,b=b?n(this.max):this.max;c>a||null===a?a=c:b<a&&(a=b);return this.translate(a,0,1,0,1)},autoLabelAlign:function(a){a=(l(a,0)-90*this.side+720)%360;return 15<a&&165>a?"right":195<a&&345>a?"left":"center"},getOffset:function(){var a=this,b=a.chart,c=b.renderer,d=a.options,e=a.tickPositions,
f=a.ticks,g=a.horiz,h=a.side,k=b.inverted?[1,0,3,2][h]:h,v,m,w=0,n,r=0,q=d.title,s=d.labels,u=0,A=b.axisOffset,b=b.clipOffset,J=[-1,1,1,-1][h],y,B=1,D=l(s.maxStaggerLines,5),F,H,G,K,ca;a.hasData=v=a.hasVisibleSeries||p(a.min)&&p(a.max)&&!!e;a.showAxis=m=v||l(d.showEmpty,!0);a.staggerLines=a.horiz&&s.staggerLines;a.axisGroup||(a.gridGroup=c.g("grid").attr({zIndex:d.gridZIndex||1}).add(),a.axisGroup=c.g("axis").attr({zIndex:d.zIndex||2}).add(),a.labelGroup=c.g("axis-labels").attr({zIndex:s.zIndex||
7}).addClass("highcharts-"+a.coll.toLowerCase()+"-labels").add());if(v||a.isLinked){a.labelAlign=l(s.align||a.autoLabelAlign(s.rotation));t(e,function(b){f[b]?f[b].addLabel():f[b]=new ia(a,b)});if(a.horiz&&!a.staggerLines&&D&&!s.rotation){for(v=a.reversed?[].concat(e).reverse():e;B<D;){F=[];H=!1;for(y=0;y<v.length;y++)G=v[y],K=(K=f[G].label&&f[G].label.getBBox())?K.width:0,ca=y%B,K&&(G=a.translate(G),F[ca]!==C&&G<F[ca]&&(H=!0),F[ca]=G+K);if(H)B++;else break}1<B&&(a.staggerLines=B)}t(e,function(b){if(0===
h||2===h||{1:"left",3:"right"}[h]===a.labelAlign)u=x(f[b].getLabelSize(),u)});a.staggerLines&&(u*=a.staggerLines,a.labelOffset=u)}else for(y in f)f[y].destroy(),delete f[y];q&&q.text&&!1!==q.enabled&&(a.axisTitle||(a.axisTitle=c.text(q.text,0,0,q.useHTML).attr({zIndex:7,rotation:q.rotation||0,align:q.textAlign||{low:"left",middle:"center",high:"right"}[q.align]}).addClass("highcharts-"+this.coll.toLowerCase()+"-title").css(q.style).add(a.axisGroup),a.axisTitle.isNew=!0),m&&(w=a.axisTitle.getBBox()[g?
"height":"width"],n=q.offset,r=p(n)?0:l(q.margin,g?5:10)),a.axisTitle[m?"show":"hide"]());a.offset=J*l(d.offset,A[h]);c=2===h?a.tickBaseline:0;g=u+r+(u&&J*(g?l(s.y,a.tickBaseline+8):s.x)-c);a.axisTitleMargin=l(n,g);A[h]=x(A[h],a.axisTitleMargin+w+J*a.offset,g);b[k]=x(b[k],2*R(d.lineWidth/2))},getLinePath:function(a){var b=this.chart,c=this.opposite,d=this.offset,e=this.horiz,f=this.left+(c?this.width:0)+d,d=b.chartHeight-this.bottom-(c?this.height:0)+d;c&&(a*=-1);return b.renderer.crispLine(["M",
e?this.left:f,e?d:this.top,"L",e?b.chartWidth-this.right:f,e?d:b.chartHeight-this.bottom],a)},getTitlePosition:function(){var a=this.horiz,b=this.left,c=this.top,d=this.len,e=this.options.title,f=a?b:c,g=this.opposite,h=this.offset,k=s(e.style.fontSize||12),d={low:f+(a?0:d),middle:f+d/2,high:f+(a?d:0)}[e.align],b=(a?c+this.height:b)+(a?1:-1)*(g?-1:1)*this.axisTitleMargin+(2===this.side?k:0);return{x:a?d:b+(g?this.width:0)+h+(e.x||0),y:a?b-(g?this.height:0)+h:d+(e.y||0)}},render:function(){var a=this,
b=a.horiz,c=a.reversed,d=a.chart,e=d.renderer,f=a.options,g=a.isLog,h=a.isLinked,k=a.tickPositions,l,m=a.axisTitle,w=a.ticks,q=a.minorTicks,r=a.alternateBands,s=f.stackLabels,u=f.alternateGridColor,x=a.tickmarkOffset,y=f.lineWidth,A=d.hasRendered&&p(a.oldMin)&&!isNaN(a.oldMin),B=a.hasData,D=a.showAxis,F,G=f.labels.overflow,H=a.justifyLabels=b&&!1!==G,I;a.labelEdge.length=0;a.justifyToPlot="justify"===G;t([w,q,r],function(a){for(var b in a)a[b].isActive=!1});if(B||h)a.minorTickInterval&&!a.categories&&
t(a.getMinorTickPositions(),function(b){q[b]||(q[b]=new ia(a,b,"minor"));A&&q[b].isNew&&q[b].render(null,!0);q[b].render(null,!1,1)}),k.length&&(l=k.slice(),(b&&c||!b&&!c)&&l.reverse(),H&&(l=l.slice(1).concat([l[0]])),t(l,function(b,c){H&&(c=c===l.length-1?0:c+1);if(!h||b>=a.min&&b<=a.max)w[b]||(w[b]=new ia(a,b)),A&&w[b].isNew&&w[b].render(c,!0,.1),w[b].render(c)}),x&&0===a.min&&(w[-1]||(w[-1]=new ia(a,-1,null,!0)),w[-1].render(-1))),u&&t(k,function(b,c){0===c%2&&b<a.max&&(r[b]||(r[b]=new ba.PlotLineOrBand(a)),
F=b+x,I=k[c+1]!==C?k[c+1]+x:a.max,r[b].options={from:g?n(F):F,to:g?n(I):I,color:u},r[b].render(),r[b].isActive=!0)}),a._addedPlotLB||(t((f.plotLines||[]).concat(f.plotBands||[]),function(b){a.addPlotBandOrLine(b)}),a._addedPlotLB=!0);t([w,q,r],function(a){var b,c,e=[],f=S?S.duration||500:0,g=function(){for(c=e.length;c--;)a[e[c]]&&!a[e[c]].isActive&&(a[e[c]].destroy(),delete a[e[c]])};for(b in a)a[b].isActive||(a[b].render(b,!1,0),a[b].isActive=!1,e.push(b));a!==r&&d.hasRendered&&f?f&&setTimeout(g,
f):g()});y&&(b=a.getLinePath(y),a.axisLine?a.axisLine.animate({d:b}):a.axisLine=e.path(b).attr({stroke:f.lineColor,"stroke-width":y,zIndex:7}).add(a.axisGroup),a.axisLine[D?"show":"hide"]());m&&D&&(m[m.isNew?"attr":"animate"](a.getTitlePosition()),m.isNew=!1);s&&s.enabled&&a.renderStackTotals();a.isDirty=!1},redraw:function(){this.render();t(this.plotLinesAndBands,function(a){a.render()});t(this.series,function(a){a.isDirty=!0})},destroy:function(a){var b=this,c=b.stacks,d,e=b.plotLinesAndBands;a||
T(b);for(d in c)va(c[d]),c[d]=null;t([b.ticks,b.minorTicks,b.alternateBands],function(a){va(a)});for(a=e.length;a--;)e[a].destroy();t("stackTotalGroup axisLine axisTitle axisGroup cross gridGroup labelGroup".split(" "),function(a){b[a]&&(b[a]=b[a].destroy())});this.cross&&this.cross.destroy()},drawCrosshair:function(a,b){if(this.crosshair)if(!1===(p(b)||!l(this.crosshair.snap,!0)))this.hideCrosshair();else{var c,d=this.crosshair,e=d.animation;l(d.snap,!0)?p(b)&&(c=this.chart.inverted!=this.horiz?
b.plotX:this.len-b.plotY):c=this.horiz?a.chartX-this.pos:this.len-a.chartY+this.pos;c=this.isRadial?this.getPlotLinePath(this.isXAxis?b.x:l(b.stackY,b.y)):this.getPlotLinePath(null,null,null,null,c);if(null===c)this.hideCrosshair();else if(this.cross)this.cross.attr({visibility:"visible"})[e?"animate":"attr"]({d:c},e);else e={"stroke-width":d.width||1,stroke:d.color||"#C0C0C0",zIndex:d.zIndex||2},d.dashStyle&&(e.dashstyle=d.dashStyle),this.cross=this.chart.renderer.path(c).attr(e).add()}},hideCrosshair:function(){this.cross&&
this.cross.hide()}};u(ya.prototype,void 0);var Na=ba.Legend=function(a,b){this.init(a,b)};Na.prototype={init:function(a,b){var c=this,d=b.itemStyle,e=l(b.padding,8),f=b.itemMarginTop||0;this.options=b;b.enabled&&(c.itemStyle=d,c.itemHiddenStyle=A(d,b.itemHiddenStyle),c.itemMarginTop=f,c.padding=e,c.initialItemX=e,c.initialItemY=e-5,c.maxItemWidth=0,c.chart=a,c.itemHeight=0,c.lastLineHeight=0,c.symbolWidth=l(b.symbolWidth,16),c.pages=[],c.render(),L(c.chart,"endResize",function(){c.positionCheckboxes()}))},
colorizeItem:function(a,b){var c=this.options,d=a.legendItem,e=a.legendLine,f=a.legendSymbol,g=this.itemHiddenStyle.color,c=b?c.itemStyle.color:g,h=b?a.legendColor||a.color||"#CCC":g,g=a.options&&a.options.marker,k={fill:h},l;d&&d.css({fill:c,color:c});e&&e.attr({stroke:h});if(f){if(g&&f.isMarker)for(l in k.stroke=h,g=a.convertAttribs(g),g)d=g[l],d!==C&&(k[l]=d);f.attr(k)}},positionItem:function(a){var b=this.options,c=b.symbolPadding,b=!b.rtl,d=a._legendItemPos,e=d[0],d=d[1],f=a.checkbox;a.legendGroup&&
a.legendGroup.translate(b?e:this.legendWidth-e-2*c-4,d);f&&(f.x=e,f.y=d)},destroyItem:function(a){var b=a.checkbox;t(["legendItem","legendLine","legendSymbol","legendGroup"],function(b){a[b]&&(a[b]=a[b].destroy())});b&&wa(a.checkbox)},destroy:function(){var a=this.group,b=this.box;b&&(this.box=b.destroy());a&&(this.group=a.destroy())},positionCheckboxes:function(a){var b=this.group.alignAttr,c,d=this.clipHeight||this.legendHeight;b&&(c=b.translateY,t(this.allItems,function(e){var f=e.checkbox,g;f&&
(g=c+f.y+(a||0)+3,P(f,{left:b.translateX+e.checkboxOffset+f.x-20+"px",top:g+"px",display:g>c-6&&g<c+d-6?"":"none"}))}))},renderTitle:function(){var a=this.padding,b=this.options.title,c=0;b.text&&(this.title||(this.title=this.chart.renderer.label(b.text,a-3,a-4,null,null,null,null,null,"legend-title").attr({zIndex:1}).css(b.style).add(this.group)),a=this.title.getBBox(),c=a.height,this.offsetWidth=a.width,this.contentGroup.attr({translateY:c}));this.titleHeight=c},renderItem:function(a){var b=this.chart,
c=b.renderer,d=this.options,e="horizontal"===d.layout,f=this.symbolWidth,g=d.symbolPadding,h=this.itemStyle,k=this.itemHiddenStyle,v=this.padding,p=e?l(d.itemDistance,20):0,w=!d.rtl,m=d.width,r=d.itemMarginBottom||0,n=this.itemMarginTop,q=this.initialItemX,s=a.legendItem,t=a.series&&a.series.drawLegendSymbol?a.series:a,u=t.options,u=this.createCheckboxForItem&&u&&u.showCheckbox,y=d.useHTML;s||(a.legendGroup=c.g("legend-item").attr({zIndex:1}).add(this.scrollGroup),a.legendItem=s=c.text(d.labelFormat?
sa(d.labelFormat,a):d.labelFormatter.call(a),w?f+g:-g,this.baseline||0,y).css(A(a.visible?h:k)).attr({align:w?"left":"right",zIndex:2}).add(a.legendGroup),this.baseline||(this.baseline=c.fontMetrics(h.fontSize,s).f+3+n,s.attr("y",this.baseline)),t.drawLegendSymbol(this,a),this.setItemEvents&&this.setItemEvents(a,s,y,h,k),this.colorizeItem(a,a.visible),u&&this.createCheckboxForItem(a));c=s.getBBox();f=a.checkboxOffset=d.itemWidth||a.legendItemWidth||f+g+c.width+p+(u?20:0);this.itemHeight=g=B(a.legendItemHeight||
c.height);e&&this.itemX-q+f>(m||b.chartWidth-2*v-q-d.x)&&(this.itemX=q,this.itemY+=n+this.lastLineHeight+r,this.lastLineHeight=0);this.maxItemWidth=x(this.maxItemWidth,f);this.lastItemY=n+this.itemY+r;this.lastLineHeight=x(g,this.lastLineHeight);a._legendItemPos=[this.itemX,this.itemY];e?this.itemX+=f:(this.itemY+=n+g+r,this.lastLineHeight=g);this.offsetWidth=m||x((e?this.itemX-q-p:f)+v,this.offsetWidth)},getAllItems:function(){var a=[];t(this.chart.series,function(b){var c=b.options;l(c.showInLegend,
p(c.linkedTo)?!1:C,!0)&&(a=a.concat(b.legendItems||("point"===c.legendType?b.data:b)))});return a},render:function(){var a=this,b=a.chart,c=b.renderer,d=a.group,e,f,g,h,k=a.box,l=a.options,p=a.padding,m=l.borderWidth,n=l.backgroundColor;a.itemX=a.initialItemX;a.itemY=a.initialItemY;a.offsetWidth=0;a.lastItemY=0;d||(a.group=d=c.g("legend").attr({zIndex:7}).add(),a.contentGroup=c.g().attr({zIndex:1}).add(d),a.scrollGroup=c.g().add(a.contentGroup));a.renderTitle();e=a.getAllItems();Ea(e,function(a,b){return(a.options&&
a.options.legendIndex||0)-(b.options&&b.options.legendIndex||0)});l.reversed&&e.reverse();a.allItems=e;a.display=f=!!e.length;t(e,function(b){a.renderItem(b)});g=l.width||a.offsetWidth;h=a.lastItemY+a.lastLineHeight+a.titleHeight;h=a.handleOverflow(h);if(m||n)g+=p,h+=p,k?0<g&&0<h&&(k[k.isNew?"attr":"animate"](k.crisp({width:g,height:h})),k.isNew=!1):(a.box=k=c.rect(0,0,g,h,l.borderRadius,m||0).attr({stroke:l.borderColor,"stroke-width":m||0,fill:n||"none"}).add(d).shadow(l.shadow),k.isNew=!0),k[f?
"show":"hide"]();a.legendWidth=g;a.legendHeight=h;t(e,function(b){a.positionItem(b)});f&&d.align(u({width:g,height:h},l),!0,"spacingBox");b.isResizing||this.positionCheckboxes()},handleOverflow:function(a){var b=this,c=this.chart,d=c.renderer,e=this.options,f=e.y,f=c.spacingBox.height+("top"===e.verticalAlign?-f:f)-this.padding,g=e.maxHeight,h,k=this.clipRect,p=e.navigation,m=l(p.animation,!0),w=p.arrowSize||12,n=this.nav,r=this.pages,q,s=this.allItems;"horizontal"===e.layout&&(f/=2);g&&(f=U(f,g));
r.length=0;a>f&&!e.useHTML?(this.clipHeight=h=x(f-20-this.titleHeight-this.padding,0),this.currentPage=l(this.currentPage,1),this.fullHeight=a,t(s,function(a,b){var c=a._legendItemPos[1],d=B(a.legendItem.getBBox().height),e=r.length;if(!e||c-r[e-1]>h&&(q||c)!==r[e-1])r.push(q||c),e++;b===s.length-1&&c+d-r[e-1]>h&&r.push(c);c!==q&&(q=c)}),k||(k=b.clipRect=d.clipRect(0,this.padding,9999,0),b.contentGroup.clip(k)),k.attr({height:h}),n||(this.nav=n=d.g().attr({zIndex:1}).add(this.group),this.up=d.symbol("triangle",
0,0,w,w).on("click",function(){b.scroll(-1,m)}).add(n),this.pager=d.text("",15,10).css(p.style).add(n),this.down=d.symbol("triangle-down",0,0,w,w).on("click",function(){b.scroll(1,m)}).add(n)),b.scroll(0),a=f):n&&(k.attr({height:c.chartHeight}),n.hide(),this.scrollGroup.attr({translateY:1}),this.clipHeight=0);return a},scroll:function(a,b){var c=this.pages,d=c.length,e=this.currentPage+a,f=this.clipHeight,g=this.options.navigation,h=g.activeColor,g=g.inactiveColor,k=this.pager,p=this.padding;e>d&&
(e=d);0<e&&(b!==C&&(S=l(b,this.chart.animation)),this.nav.attr({translateX:p,translateY:f+this.padding+7+this.titleHeight,visibility:"visible"}),this.up.attr({fill:1===e?g:h}).css({cursor:1===e?"default":"pointer"}),k.attr({text:e+"/"+d}),this.down.attr({x:18+this.pager.getBBox().width,fill:e===d?g:h}).css({cursor:e===d?"default":"pointer"}),c=-c[e-1]+this.initialItemY,this.scrollGroup.animate({translateY:c}),this.currentPage=e,this.positionCheckboxes(c))}};var sb=ba.LegendSymbolMixin={drawRectangle:function(a,
b){var c=a.options.symbolHeight||12;b.legendSymbol=this.chart.renderer.rect(0,a.baseline-5-c/2,a.symbolWidth,c,a.options.symbolRadius||0).attr({zIndex:3}).add(b.legendGroup)},drawLineMarker:function(a){var b=this.options,c=b.marker,d;d=a.symbolWidth;var e=this.chart.renderer,f=this.legendGroup;a=a.baseline-B(.3*e.fontMetrics(a.options.itemStyle.fontSize,this.legendItem).b);var g;b.lineWidth&&(g={"stroke-width":b.lineWidth},b.dashStyle&&(g.dashstyle=b.dashStyle),this.legendLine=e.path(["M",0,a,"L",
d,a]).attr(g).add(f));c&&!1!==c.enabled&&(b=c.radius,this.legendSymbol=d=e.symbol(this.symbol,d/2-b,a-b,2*b,2*b).add(f),d.isMarker=!0)}};(/Trident\/7\.0/.test(fa)||Aa)&&Qa(Na.prototype,"positionItem",function(a,b){var c=this,d=function(){b._legendItemPos&&a.call(c,b)};d();setTimeout(d)});Fa.prototype={init:function(a,b){var c,d=a.series;a.series=null;c=A(F,a);c.series=a.series=d;this.userOptions=a;d=c.chart;this.margin=this.splashArray("margin",d);this.spacing=this.splashArray("spacing",d);var e=
d.events;this.bounds={h:{},v:{}};this.callback=b;this.isResizing=0;this.options=c;this.axes=[];this.series=[];this.hasCartesianSeries=d.showAxes;var f=this,g;f.index=ga.length;ga.push(f);db++;!1!==d.reflow&&L(f,"load",function(){f.initReflow()});if(e)for(g in e)L(f,g,e[g]);f.xAxis=[];f.yAxis=[];f.animation=Z?!1:l(d.animation,!0);f.pointCount=f.colorCounter=f.symbolCounter=0;f.firstRender()},initSeries:function(a){var b=this.options.chart;(b=pa[a.type||b.type||b.defaultSeriesType])||O(17,!0);b=new b;
b.init(this,a);return b},isInsidePlot:function(a,b,c){var d=c?b:a;a=c?a:b;return 0<=d&&d<=this.plotWidth&&0<=a&&a<=this.plotHeight},adjustTickAmounts:function(){!1!==this.options.chart.alignTicks&&t(this.axes,function(a){a.adjustTickAmount()});this.maxTicks=null},redraw:function(a){var b=this.axes,c=this.series,d=this.pointer,e=this.legend,f=this.isDirtyLegend,g,h,k=this.hasCartesianSeries,p=this.isDirtyBox,m=c.length,w=m,n=this.renderer,r=n.isHidden(),q=[];S=l(a,this.animation);r&&this.cloneRenderTo();
for(this.layOutTitles();w--;)if(a=c[w],a.options.stacking&&(g=!0,a.isDirty)){h=!0;break}if(h)for(w=m;w--;)a=c[w],a.options.stacking&&(a.isDirty=!0);t(c,function(a){a.isDirty&&"point"===a.options.legendType&&(f=!0)});f&&e.options.enabled&&(e.render(),this.isDirtyLegend=!1);g&&this.getStacks();k&&(this.isResizing||(this.maxTicks=null,t(b,function(a){a.setScale()})),this.adjustTickAmounts());this.getMargins();k&&(t(b,function(a){a.isDirty&&(p=!0)}),t(b,function(a){a.isDirtyExtremes&&(a.isDirtyExtremes=
!1,q.push(function(){M(a,"afterSetExtremes",u(a.eventArgs,a.getExtremes()));delete a.eventArgs}));(p||g)&&a.redraw()}));p&&this.drawChartBox();t(c,function(a){a.isDirty&&a.visible&&(!a.isCartesian||a.xAxis)&&a.redraw()});d&&d.reset(!0);n.draw();M(this,"redraw");r&&this.cloneRenderTo(!0);t(q,function(a){a.call()})},get:function(a){var b=this.axes,c=this.series,d,e;for(d=0;d<b.length;d++)if(b[d].options.id===a)return b[d];for(d=0;d<c.length;d++)if(c[d].options.id===a)return c[d];for(d=0;d<c.length;d++)for(e=
c[d].points||[],b=0;b<e.length;b++)if(e[b].id===a)return e[b];return null},getAxes:function(){var a=this,b=this.options,c=b.xAxis=la(b.xAxis||{}),b=b.yAxis=la(b.yAxis||{});t(c,function(a,b){a.index=b;a.isX=!0});t(b,function(a,b){a.index=b});c=c.concat(b);t(c,function(b){new ya(a,b)});a.adjustTickAmounts()},getSelectedPoints:function(){var a=[];t(this.series,function(b){a=a.concat(eb(b.points||[],function(a){return a.selected}))});return a},getSelectedSeries:function(){return eb(this.series,function(a){return a.selected})},
getStacks:function(){var a=this;t(a.yAxis,function(a){a.stacks&&a.hasVisibleSeries&&(a.oldStacks=a.stacks)});t(a.series,function(b){!b.options.stacking||!0!==b.visible&&!1!==a.options.chart.ignoreHiddenSeries||(b.stackKey=b.type+l(b.options.stack,""))})},setTitle:function(a,b,c){var d=this,e=d.options,f;f=e.title=A(e.title,a);e=e.subtitle=A(e.subtitle,b);t([["title",a,f],["subtitle",b,e]],function(a){var b=a[0],c=d[b],e=a[1];a=a[2];c&&e&&(d[b]=c=c.destroy());a&&a.text&&!c&&(d[b]=d.renderer.text(a.text,
0,0,a.useHTML).attr({align:a.align,"class":"highcharts-"+b,zIndex:a.zIndex||4}).css(a.style).add())});d.layOutTitles(c)},layOutTitles:function(a){var b=0,c=this.title,d=this.subtitle,e=this.options,f=e.title,e=e.subtitle,g=this.renderer,h=this.spacingBox.width-44;c&&(c.css({width:(f.width||h)+"px"}).align(u({y:g.fontMetrics(f.style.fontSize,c).b-3},f),!1,"spacingBox"),f.floating||f.verticalAlign||(b=c.getBBox().height));d&&(d.css({width:(e.width||h)+"px"}).align(u({y:b+(f.margin-13)+g.fontMetrics(f.style.fontSize,
d).b},e),!1,"spacingBox"),e.floating||e.verticalAlign||(b=ja(b+d.getBBox().height)));c=this.titleOffset!==b;this.titleOffset=b;!this.isDirtyBox&&c&&(this.isDirtyBox=c,this.hasRendered&&l(a,!0)&&this.isDirtyBox&&this.redraw())},getChartSize:function(){var a=this.options.chart,b=a.width,a=a.height,c=this.renderToClone||this.renderTo;p(b)||(this.containerWidth=Ca(c,"width"));p(a)||(this.containerHeight=Ca(c,"height"));this.chartWidth=x(0,b||this.containerWidth||600);this.chartHeight=x(0,l(a,19<this.containerHeight?
this.containerHeight:400))},cloneRenderTo:function(a){var b=this.renderToClone,c=this.container;a?b&&(this.renderTo.appendChild(c),wa(b),delete this.renderToClone):(c&&c.parentNode===this.renderTo&&this.renderTo.removeChild(c),this.renderToClone=b=this.renderTo.cloneNode(0),P(b,{position:"absolute",top:"-9999px",display:"block"}),b.style.setProperty&&b.style.setProperty("display","block","important"),D.body.appendChild(b),c&&b.appendChild(c))},getContainer:function(){var a,b=this.options.chart,c,
d,e;this.renderTo=a=b.renderTo;e="highcharts-"+Ga++;W(a)&&(this.renderTo=a=D.getElementById(a));a||O(13,!0);c=s(m(a,"data-highcharts-chart"));!isNaN(c)&&ga[c]&&ga[c].hasRendered&&ga[c].destroy();m(a,"data-highcharts-chart",this.index);a.innerHTML="";b.skipClone||a.offsetWidth||this.cloneRenderTo();this.getChartSize();c=this.chartWidth;d=this.chartHeight;this.container=a=ma("div",{className:"highcharts-container"+(b.className?" "+b.className:""),id:e},u({position:"relative",overflow:"hidden",width:c+
"px",height:d+"px",textAlign:"left",lineHeight:"normal",zIndex:0,"-webkit-tap-highlight-color":"rgba(0,0,0,0)"},b.style),this.renderToClone||a);this._cursor=a.style.cursor;this.renderer=b.forExport?new ra(a,c,d,b.style,!0):new ra(a,c,d,b.style);Z&&this.renderer.create(this,a,c,d)},getMargins:function(){var a=this.spacing,b,c=this.legend,d=this.margin,e=this.options.legend,f=l(e.margin,20),g=e.x,h=e.y,k=e.align,m=e.verticalAlign,n=this.titleOffset;this.resetMargins();b=this.axisOffset;n&&!p(d[0])&&
(this.plotTop=x(this.plotTop,n+this.options.title.margin+a[0]));c.display&&!e.floating&&("right"===k?p(d[1])||(this.marginRight=x(this.marginRight,c.legendWidth-g+f+a[1])):"left"===k?p(d[3])||(this.plotLeft=x(this.plotLeft,c.legendWidth+g+f+a[3])):"top"===m?p(d[0])||(this.plotTop=x(this.plotTop,c.legendHeight+h+f+a[0])):"bottom"!==m||p(d[2])||(this.marginBottom=x(this.marginBottom,c.legendHeight-h+f+a[2])));this.extraBottomMargin&&(this.marginBottom+=this.extraBottomMargin);this.extraTopMargin&&(this.plotTop+=
this.extraTopMargin);this.hasCartesianSeries&&t(this.axes,function(a){a.getOffset()});p(d[3])||(this.plotLeft+=b[3]);p(d[0])||(this.plotTop+=b[0]);p(d[2])||(this.marginBottom+=b[2]);p(d[1])||(this.marginRight+=b[1]);this.setChartSize()},reflow:function(a){var b=this,c=b.options.chart,d=b.renderTo,e=c.width||Ca(d,"width"),f=c.height||Ca(d,"height"),c=a?a.target:H,d=function(){b.container&&(b.setSize(e,f,!1),b.hasUserSize=null)};if(!b.hasUserSize&&e&&f&&(c===H||c===D)){if(e!==b.containerWidth||f!==
b.containerHeight)clearTimeout(b.reflowTimeout),a?b.reflowTimeout=setTimeout(d,100):d();b.containerWidth=e;b.containerHeight=f}},initReflow:function(){var a=this,b=function(b){a.reflow(b)};L(H,"resize",b);L(a,"destroy",function(){T(H,"resize",b)})},setSize:function(a,b,c){var d=this,e,f,g;d.isResizing+=1;g=function(){d&&M(d,"endResize",null,function(){d.isResizing-=1})};S=l(c,d.animation);d.oldChartHeight=d.chartHeight;d.oldChartWidth=d.chartWidth;p(a)&&(d.chartWidth=e=x(0,B(a)),d.hasUserSize=!!e);
p(b)&&(d.chartHeight=f=x(0,B(b)));(S?gb:P)(d.container,{width:e+"px",height:f+"px"},S);d.setChartSize(!0);d.renderer.setSize(e,f,c);d.maxTicks=null;t(d.axes,function(a){a.isDirty=!0;a.setScale()});t(d.series,function(a){a.isDirty=!0});d.isDirtyLegend=!0;d.isDirtyBox=!0;d.layOutTitles();d.getMargins();d.redraw(c);d.oldChartHeight=null;M(d,"resize");!1===S?g():setTimeout(g,S&&S.duration||500)},setChartSize:function(a){var b=this.inverted,c=this.renderer,d=this.chartWidth,e=this.chartHeight,f=this.options.chart,
g=this.spacing,h=this.clipOffset,k,l,p,m;this.plotLeft=k=B(this.plotLeft);this.plotTop=l=B(this.plotTop);this.plotWidth=p=x(0,B(d-k-this.marginRight));this.plotHeight=m=x(0,B(e-l-this.marginBottom));this.plotSizeX=b?m:p;this.plotSizeY=b?p:m;this.plotBorderWidth=f.plotBorderWidth||0;this.spacingBox=c.spacingBox={x:g[3],y:g[0],width:d-g[3]-g[1],height:e-g[0]-g[2]};this.plotBox=c.plotBox={x:k,y:l,width:p,height:m};d=2*R(this.plotBorderWidth/2);b=ja(x(d,h[3])/2);c=ja(x(d,h[0])/2);this.clipBox={x:b,y:c,
width:R(this.plotSizeX-x(d,h[1])/2-b),height:x(0,R(this.plotSizeY-x(d,h[2])/2-c))};a||t(this.axes,function(a){a.setAxisSize();a.setAxisTranslation()})},resetMargins:function(){var a=this.spacing,b=this.margin;this.plotTop=l(b[0],a[0]);this.marginRight=l(b[1],a[1]);this.marginBottom=l(b[2],a[2]);this.plotLeft=l(b[3],a[3]);this.axisOffset=[0,0,0,0];this.clipOffset=[0,0,0,0]},drawChartBox:function(){var a=this.options.chart,b=this.renderer,c=this.chartWidth,d=this.chartHeight,e=this.chartBackground,
f=this.plotBackground,g=this.plotBorder,h=this.plotBGImage,k=a.borderWidth||0,l=a.backgroundColor,p=a.plotBackgroundColor,m=a.plotBackgroundImage,n=a.plotBorderWidth||0,r,q=this.plotLeft,s=this.plotTop,t=this.plotWidth,u=this.plotHeight,x=this.plotBox,y=this.clipRect,A=this.clipBox;r=k+(a.shadow?8:0);if(k||l)e?e.animate(e.crisp({width:c-r,height:d-r})):(e={fill:l||"none"},k&&(e.stroke=a.borderColor,e["stroke-width"]=k),this.chartBackground=b.rect(r/2,r/2,c-r,d-r,a.borderRadius,k).attr(e).addClass("highcharts-background").add().shadow(a.shadow));
p&&(f?f.animate(x):this.plotBackground=b.rect(q,s,t,u,0).attr({fill:p}).add().shadow(a.plotShadow));m&&(h?h.animate(x):this.plotBGImage=b.image(m,q,s,t,u).add());y?y.animate({width:A.width,height:A.height}):this.clipRect=b.clipRect(A);n&&(g?g.animate(g.crisp({x:q,y:s,width:t,height:u,strokeWidth:-n})):this.plotBorder=b.rect(q,s,t,u,0,-n).attr({stroke:a.plotBorderColor,"stroke-width":n,fill:"none",zIndex:1}).add());this.isDirtyBox=!1},propFromSeries:function(){var a=this,b=a.options.chart,c,d=a.options.series,
e,f;t(["inverted","angular","polar"],function(g){c=pa[b.type||b.defaultSeriesType];f=a[g]||b[g]||c&&c.prototype[g];for(e=d&&d.length;!f&&e--;)(c=pa[d[e].type])&&c.prototype[g]&&(f=!0);a[g]=f})},linkSeries:function(){var a=this,b=a.series;t(b,function(a){a.linkedSeries.length=0});t(b,function(b){var d=b.options.linkedTo;W(d)&&(d=":previous"===d?a.series[b.index-1]:a.get(d))&&(d.linkedSeries.push(b),b.linkedParent=d)})},renderSeries:function(){t(this.series,function(a){a.translate();a.setTooltipPoints&&
a.setTooltipPoints();a.render()})},renderLabels:function(){var a=this,b=a.options.labels;b.items&&t(b.items,function(c){var d=u(b.style,c.style),e=s(d.left)+a.plotLeft,f=s(d.top)+a.plotTop+12;delete d.left;delete d.top;a.renderer.text(c.html,e,f).attr({zIndex:2}).css(d).add()})},render:function(){var a=this.axes,b=this.renderer,c=this.options;this.setTitle();this.legend=new Na(this,c.legend);this.getStacks();t(a,function(a){a.setScale()});this.getMargins();this.maxTicks=null;t(a,function(a){a.setTickPositions(!0);
a.setMaxTicks()});this.adjustTickAmounts();this.getMargins();this.drawChartBox();this.hasCartesianSeries&&t(a,function(a){a.render()});this.seriesGroup||(this.seriesGroup=b.g("series-group").attr({zIndex:3}).add());this.renderSeries();this.renderLabels();this.showCredits(c.credits);this.hasRendered=!0},showCredits:function(a){a.enabled&&!this.credits&&(this.credits=this.renderer.text(a.text,0,0).on("click",function(){a.href&&(location.href=a.href)}).attr({align:a.position.align,zIndex:8}).css(a.style).add().align(a.position))},
destroy:function(){var a=this,b=a.axes,c=a.series,d=a.container,e,f=d&&d.parentNode;M(a,"destroy");ga[a.index]=C;db--;a.renderTo.removeAttribute("data-highcharts-chart");T(a);for(e=b.length;e--;)b[e]=b[e].destroy();for(e=c.length;e--;)c[e]=c[e].destroy();t("title subtitle chartBackground plotBackground plotBGImage plotBorder seriesGroup clipRect credits pointer scroller rangeSelector legend resetZoomButton tooltip renderer".split(" "),function(b){var c=a[b];c&&c.destroy&&(a[b]=c.destroy())});d&&(d.innerHTML=
"",T(d),f&&wa(d));for(e in a)delete a[e]},isReadyToRender:function(){var a=this;return!Q&&H==H.top&&"complete"!==D.readyState||Z&&!H.canvg?(Z?CanVGController.push(function(){a.firstRender()},a.options.global.canvasToolsURL):D.attachEvent("onreadystatechange",function(){D.detachEvent("onreadystatechange",a.firstRender);"complete"===D.readyState&&a.firstRender()}),!1):!0},firstRender:function(){var a=this,b=a.options,c=a.callback;a.isReadyToRender()&&(a.getContainer(),M(a,"init"),a.resetMargins(),a.setChartSize(),
a.propFromSeries(),a.getAxes(),t(b.series||[],function(b){a.initSeries(b)}),a.linkSeries(),M(a,"beforeRender"),ba.Pointer&&(a.pointer=new Pointer(a,b)),a.render(),a.renderer.draw(),c&&c.apply(a,[a]),t(a.callbacks,function(b){b.apply(a,[a])}),a.cloneRenderTo(!0),M(a,"load"))},splashArray:function(a,b){var c=b[a],c=y(c)?c:[c,c,c,c];return[l(b[a+"Top"],c[0]),l(b[a+"Right"],c[1]),l(b[a+"Bottom"],c[2]),l(b[a+"Left"],c[3])]}};Fa.prototype.callbacks=[];var Da=function(){};Da.prototype={init:function(a,b,
c){this.series=a;this.applyOptions(b,c);this.pointAttr={};a.options.colorByPoint&&(b=a.options.colors||a.chart.options.colors,this.color=this.color||b[a.colorCounter++],a.colorCounter===b.length&&(a.colorCounter=0));a.chart.pointCount++;return this},applyOptions:function(a,b){var c=this.series,d=c.options.pointValKey||c.pointValKey;a=Da.prototype.optionsToObject.call(this,a);u(this,a);this.options=this.options?u(this.options,a):a;d&&(this.y=this[d]);this.x===C&&c&&(this.x=b===C?c.autoIncrement():
b);return this},optionsToObject:function(a){var b={},c=this.series,d=c.pointArrayMap||["y"],e=d.length,f=0,g=0;if("number"===typeof a||null===a)b[d[0]]=a;else if(aa(a))for(a.length>e&&(c=typeof a[0],"string"===c?b.name=a[0]:"number"===c&&(b.x=a[0]),f++);g<e;)b[d[g++]]=a[f++];else"object"===typeof a&&(b=a,a.dataLabels&&(c._hasPointLabels=!0),a.marker&&(c._hasPointMarkers=!0));return b},destroy:function(){var a=this.series.chart,b=a.hoverPoints,c;a.pointCount--;b&&(this.setState(),q(b,this),b.length||
(a.hoverPoints=null));if(this===a.hoverPoint)this.onMouseOut();if(this.graphic||this.dataLabel)T(this),this.destroyElements();this.legendItem&&a.legend.destroyItem(this);for(c in this)this[c]=null},destroyElements:function(){for(var a="graphic dataLabel dataLabelUpper group connector shadowGroup".split(" "),b,c=6;c--;)b=a[c],this[b]&&(this[b]=this[b].destroy())},getLabelConfig:function(){return{x:this.category,y:this.y,key:this.name||this.category,series:this.series,point:this,percentage:this.percentage,
total:this.total||this.stackTotal}},tooltipFormatter:function(a){var b=this.series,c=b.tooltipOptions,d=l(c.valueDecimals,""),e=c.valuePrefix||"",f=c.valueSuffix||"";t(b.pointArrayMap||["y"],function(b){b="{point."+b;if(e||f)a=a.replace(b+"}",e+b+"}"+f);a=a.replace(b+"}",b+":,."+d+"f}")});return sa(a,{point:this,series:this.series})},firePointEvent:function(a,b,c){var d=this,e=this.series.options;(e.point.events[a]||d.options&&d.options.events&&d.options.events[a])&&this.importEvents();"click"===
a&&e.allowPointSelect&&(c=function(a){d.select(null,a.ctrlKey||a.metaKey||a.shiftKey)});M(this,a,b,c)}};var Oa=function(){};Oa.prototype={isCartesian:!0,type:"line",pointClass:Da,sorted:!0,requireSorting:!0,pointAttrToOptions:{stroke:"lineColor","stroke-width":"lineWidth",fill:"fillColor",r:"radius"},axisTypes:["xAxis","yAxis"],colorCounter:0,parallelArrays:["x","y"],init:function(a,b){var c=this,d,e,f=a.series,g=function(a,b){return l(a.options.index,a._i)-l(b.options.index,b._i)};c.chart=a;c.options=
b=c.setOptions(b);c.linkedSeries=[];c.bindAxes();u(c,{name:b.name,state:"",pointAttr:{},visible:!1!==b.visible,selected:!0===b.selected});Z&&(b.animation=!1);e=b.events;for(d in e)L(c,d,e[d]);if(e&&e.click||b.point&&b.point.events&&b.point.events.click||b.allowPointSelect)a.runTrackerClick=!0;c.getColor();c.getSymbol();t(c.parallelArrays,function(a){c[a+"Data"]=[]});c.setData(b.data,!1);c.isCartesian&&(a.hasCartesianSeries=!0);f.push(c);c._i=f.length-1;Ea(f,g);this.yAxis&&Ea(this.yAxis.series,g);
t(f,function(a,b){a.index=b;a.name=a.name||"Series "+(b+1)})},bindAxes:function(){var a=this,b=a.options,c=a.chart,d;t(a.axisTypes||[],function(e){t(c[e],function(c){d=c.options;if(b[e]===d.index||b[e]!==C&&b[e]===d.id||b[e]===C&&0===d.index)c.series.push(a),a[e]=c,c.isDirty=!0});a[e]||a.optionalAxis===e||O(18,!0)})},updateParallelArrays:function(a,b){var c=a.series,d=arguments;t(c.parallelArrays,"number"===typeof b?function(d){var f="y"===d&&c.toYData?c.toYData(a):a[d];c[d+"Data"][b]=f}:function(a){Array.prototype[b].apply(c[a+
"Data"],Array.prototype.slice.call(d,2))})},autoIncrement:function(){var a=this.options,b=this.xIncrement,b=l(b,a.pointStart,0);this.pointInterval=l(this.pointInterval,a.pointInterval,1);this.xIncrement=b+this.pointInterval;return b},getSegments:function(){var a=-1,b=[],c,d=this.points,e=d.length;if(e)if(this.options.connectNulls){for(c=e;c--;)null===d[c].y&&d.splice(c,1);d.length&&(b=[d])}else t(d,function(c,g){null===c.y?(g>a+1&&b.push(d.slice(a+1,g)),a=g):g===e-1&&b.push(d.slice(a+1,g+1))});this.segments=
b},setOptions:function(a){var b=this.chart,c=b.options.plotOptions,b=b.userOptions||{},d=b.plotOptions||{},e=c[this.type];this.userOptions=a;c=A(e,c.series,a);this.tooltipOptions=A(F.tooltip,F.plotOptions[this.type].tooltip,b.tooltip,d.series&&d.series.tooltip,d[this.type]&&d[this.type].tooltip,a.tooltip);null===e.marker&&delete c.marker;return c},getCyclic:function(a,b,c){var d=this.userOptions,e="_"+a+"Index",f=a+"Counter";b||(p(d[e])?b=d[e]:(d[e]=b=this.chart[f]%c.length,this.chart[f]+=1),b=c[b]);
this[a]=b},getColor:function(){this.options.colorByPoint||this.getCyclic("color",this.options.color||Ka[this.type].color,this.chart.options.colors)},getSymbol:function(){var a=this.options.marker;this.getCyclic("symbol",a.symbol,this.chart.options.symbols);/^url/.test(this.symbol)&&(a.radius=0)},drawLegendSymbol:sb.drawLineMarker,setData:function(a,b,c,d){var e=this,f=e.points,g=f&&f.length||0,h,k=e.options,p=e.chart,m=null,n=e.xAxis,q=n&&!!n.categories,r=e.tooltipPoints,s=k.turboThreshold,u=this.xData,
x=this.yData,y=(h=e.pointArrayMap)&&h.length;a=a||[];h=a.length;b=l(b,!0);if(!1===d||!h||g!==h||e.cropped||e.hasGroupedData){e.xIncrement=null;e.pointRange=q?1:k.pointRange;e.colorCounter=0;t(this.parallelArrays,function(a){e[a+"Data"].length=0});if(s&&h>s){for(c=0;null===m&&c<h;)m=a[c],c++;if(N(m)){q=l(k.pointStart,0);k=l(k.pointInterval,1);for(c=0;c<h;c++)u[c]=q,x[c]=a[c],q+=k;e.xIncrement=q}else if(aa(m))if(y)for(c=0;c<h;c++)k=a[c],u[c]=k[0],x[c]=k.slice(1,y+1);else for(c=0;c<h;c++)k=a[c],u[c]=
k[0],x[c]=k[1];else O(12)}else for(c=0;c<h;c++)a[c]!==C&&(k={series:e},e.pointClass.prototype.applyOptions.apply(k,[a[c]]),e.updateParallelArrays(k,c),q&&k.name&&(n.names[k.x]=k.name));W(x[0])&&O(14,!0);e.data=[];e.options.data=a;for(c=g;c--;)f[c]&&f[c].destroy&&f[c].destroy();r&&(r.length=0);n&&(n.minRange=n.userMinRange);e.isDirty=e.isDirtyData=p.isDirtyBox=!0;c=!1}else t(a,function(a,b){f[b].update(a,!1,null,!1)});b&&p.redraw(c)},processData:function(a){var b=this.xData,c=this.yData,d=b.length,
e;e=0;var f,g,h=this.xAxis,k,l=this.options;k=l.cropThreshold;var p=0,m=this.isCartesian,n,r;if(m&&!this.isDirty&&!h.isDirty&&!this.yAxis.isDirty&&!a)return!1;h&&(n=h.getExtremes(),r=n.min,n=n.max);if(m&&this.sorted&&(!k||d>k||this.forceCrop))if(b[d-1]<r||b[0]>n)b=[],c=[];else if(b[0]<r||b[d-1]>n)e=this.cropData(this.xData,this.yData,r,n),b=e.xData,c=e.yData,e=e.start,f=!0,p=b.length;for(k=b.length-1;0<=k;k--)d=b[k]-b[k-1],!f&&b[k]>r&&b[k]<n&&p++,0<d&&(g===C||d<g)?g=d:0>d&&this.requireSorting&&O(15);
this.cropped=f;this.cropStart=e;this.processedXData=b;this.processedYData=c;this.activePointCount=p;null===l.pointRange&&(this.pointRange=g||1);this.closestPointRange=g},cropData:function(a,b,c,d){var e=a.length,f=0,g=e,h=l(this.cropShoulder,1),k;for(k=0;k<e;k++)if(a[k]>=c){f=x(0,k-h);break}for(;k<e;k++)if(a[k]>d){g=k+h;break}return{xData:a.slice(f,g),yData:b.slice(f,g),start:f,end:g}},generatePoints:function(){var a=this.options.data,b=this.data,c,d=this.processedXData,e=this.processedYData,f=this.pointClass,
g=d.length,h=this.cropStart||0,k,l=this.hasGroupedData,p,m=[],n;b||l||(b=[],b.length=a.length,b=this.data=b);for(n=0;n<g;n++)k=h+n,l?m[n]=(new f).init(this,[d[n]].concat(la(e[n]))):(b[k]?p=b[k]:a[k]!==C&&(b[k]=p=(new f).init(this,a[k],d[n])),m[n]=p),m[n].index=k;if(b&&(g!==(c=b.length)||l))for(n=0;n<c;n++)n!==h||l||(n+=g),b[n]&&(b[n].destroyElements(),b[n].plotX=C);this.data=b;this.points=m},getExtremes:function(a){var b=this.yAxis,c=this.processedXData,d,e=[],f=0;d=this.xAxis.getExtremes();var g=
d.min,h=d.max,k,p,m,n;a=a||this.stackedYData||this.processedYData;d=a.length;for(n=0;n<d;n++)if(p=c[n],m=a[n],k=null!==m&&m!==C&&(!b.isLog||m.length||0<m),p=this.getExtremesFromAll||this.cropped||(c[n+1]||p)>=g&&(c[n-1]||p)<=h,k&&p)if(k=m.length)for(;k--;)null!==m[k]&&(e[f++]=m[k]);else e[f++]=m;this.dataMin=l(void 0,ua(e));this.dataMax=l(void 0,na(e))},translate:function(){this.processedXData||this.processData();this.generatePoints();for(var a=this.options,b=a.stacking,c=this.xAxis,d=c.categories,
e=this.yAxis,f=this.points,g=f.length,h=!!this.modifyValue,k=a.pointPlacement,m="between"===k||N(k),n=a.threshold,a=0;a<g;a++){var q=f[a],s=q.x,r=q.y,u=q.low,t=b&&e.stacks[(this.negStacks&&r<n?"-":"")+this.stackKey];e.isLog&&0>=r&&(q.y=r=null,O(10));q.plotX=c.translate(s,0,0,0,1,k,"flags"===this.type);b&&this.visible&&t&&t[s]&&(t=t[s],r=t.points[this.index+","+a],u=r[0],r=r[1],0===u&&(u=l(n,e.min)),e.isLog&&0>=u&&(u=null),q.total=q.stackTotal=t.total,q.percentage=t.total&&q.y/t.total*100,q.stackY=
r,t.setOffset(this.pointXOffset||0,this.barW||0));q.yBottom=p(u)?e.translate(u,0,1,0,1):null;h&&(r=this.modifyValue(r,q));q.plotY="number"===typeof r&&Infinity!==r?e.translate(r,0,1,0,1):C;q.clientX=m?c.translate(s,0,0,0,1):q.plotX;q.negative=q.y<(n||0);q.category=d&&d[q.x]!==C?d[q.x]:q.x}this.getSegments()},animate:function(a){var b=this.chart,c=b.renderer,d;d=this.options.animation;var e=this.clipBox||b.clipBox,f=b.inverted,g;d&&!y(d)&&(d=Ka[this.type].animation);g=["_sharedClip",d.duration,d.easing,
e.height].join();a?(a=b[g],d=b[g+"m"],a||(b[g]=a=c.clipRect(u(e,{width:0})),b[g+"m"]=d=c.clipRect(-99,f?-b.plotLeft:-b.plotTop,99,f?b.chartWidth:b.chartHeight)),this.group.clip(a),this.markerGroup.clip(d),this.sharedClipKey=g):((a=b[g])&&a.animate({width:b.plotSizeX},d),b[g+"m"]&&b[g+"m"].animate({width:b.plotSizeX+99},d),this.animate=null)},afterAnimate:function(){var a=this.chart,b=this.sharedClipKey,c=this.group,d=this.clipBox;c&&!1!==this.options.clip&&(b&&d||c.clip(d?a.renderer.clipRect(d):a.clipRect),
this.markerGroup.clip());M(this,"afterAnimate");setTimeout(function(){b&&a[b]&&(d||(a[b]=a[b].destroy()),a[b+"m"]&&(a[b+"m"]=a[b+"m"].destroy()))},100)},drawPoints:function(){var a,b=this.points,c=this.chart,d,e,f,g,h,k,p,m,n=this.options.marker,q=this.pointAttr[""],r,s,t,x=this.markerGroup,y=l(n.enabled,!this.requireSorting||this.activePointCount<.5*this.xAxis.len/n.radius);if(!1!==n.enabled||this._hasPointMarkers)for(f=b.length;f--;)g=b[f],d=R(g.plotX),e=g.plotY,m=g.graphic,r=g.marker||{},s=!!g.marker,
a=y&&r.enabled===C||r.enabled,t=c.isInsidePlot(B(d),e,c.inverted),a&&e!==C&&!isNaN(e)&&null!==g.y?(a=g.pointAttr[g.selected?"select":""]||q,h=a.r,k=l(r.symbol,this.symbol),p=0===k.indexOf("url"),m?m[t?"show":"hide"](!0).animate(u({x:d-h,y:e-h},m.symbolName?{width:2*h,height:2*h}:{})):t&&(0<h||p)&&(g.graphic=c.renderer.symbol(k,d-h,e-h,2*h,2*h,s?r:n).attr(a).add(x))):m&&(g.graphic=m.destroy())},convertAttribs:function(a,b,c,d){var e=this.pointAttrToOptions,f,g,h={};a=a||{};b=b||{};c=c||{};d=d||{};
for(f in e)g=e[f],h[f]=l(a[g],b[f],c[f],d[f]);return h},getAttribs:function(){var a=this,b=a.options,c=Ka[a.type].marker?b.marker:b,d=c.states,e=d.hover,f,g=a.color;f={stroke:g,fill:g};var h=a.points||[],k,l=[],m,n=a.pointAttrToOptions;m=a.hasPointSpecificOptions;var q=b.negativeColor,r=c.lineColor,s=c.fillColor;k=b.turboThreshold;var x;b.marker?(e.radius=e.radius||c.radius+e.radiusPlus,e.lineWidth=e.lineWidth||c.lineWidth+e.lineWidthPlus):e.color=e.color||qa(e.color||g).brighten(e.brightness).get();
l[""]=a.convertAttribs(c,f);t(["hover","select"],function(b){l[b]=a.convertAttribs(d[b],l[""])});a.pointAttr=l;g=h.length;if(!k||g<k||m)for(;g--;){k=h[g];(c=k.options&&k.options.marker||k.options)&&!1===c.enabled&&(c.radius=0);k.negative&&q&&(k.color=k.fillColor=q);m=b.colorByPoint||k.color;if(k.options)for(x in n)p(c[n[x]])&&(m=!0);m?(c=c||{},m=[],d=c.states||{},f=d.hover=d.hover||{},b.marker||(f.color=f.color||!k.options.color&&e.color||qa(k.color).brighten(f.brightness||e.brightness).get()),f=
{color:k.color},s||(f.fillColor=k.color),r||(f.lineColor=k.color),m[""]=a.convertAttribs(u(f,c),l[""]),m.hover=a.convertAttribs(d.hover,l.hover,m[""]),m.select=a.convertAttribs(d.select,l.select,m[""])):m=l;k.pointAttr=m}},destroy:function(){var a=this,b=a.chart,c=/AppleWebKit\/533/.test(fa),d,e,f=a.data||[],g,h,k;M(a,"destroy");T(a);t(a.axisTypes||[],function(b){if(k=a[b])q(k.series,a),k.isDirty=k.forceRedraw=!0});a.legendItem&&a.chart.legend.destroyItem(a);for(e=f.length;e--;)(g=f[e])&&g.destroy&&
g.destroy();a.points=null;clearTimeout(a.animationTimeout);t("area graph dataLabelsGroup group markerGroup tracker graphNeg areaNeg posClip negClip".split(" "),function(b){a[b]&&(d=c&&"group"===b?"hide":"destroy",a[b][d]())});b.hoverSeries===a&&(b.hoverSeries=null);q(b.series,a);for(h in a)delete a[h]},getSegmentPath:function(a){var b=this,c=[],d=b.options.step;t(a,function(e,f){var g=e.plotX,h=e.plotY,k;b.getPointSpline?c.push.apply(c,b.getPointSpline(a,e,f)):(c.push(f?"L":"M"),d&&f&&(k=a[f-1],"right"===
d?c.push(k.plotX,h):"center"===d?c.push((k.plotX+g)/2,k.plotY,(k.plotX+g)/2,h):c.push(g,k.plotY)),c.push(e.plotX,e.plotY))});return c},getGraphPath:function(){var a=this,b=[],c,d=[];t(a.segments,function(e){c=a.getSegmentPath(e);1<e.length?b=b.concat(c):d.push(e[0])});a.singlePoints=d;return a.graphPath=b},drawGraph:function(){var a=this,b=this.options,c=[["graph",b.lineColor||this.color]],d=b.lineWidth,e=b.dashStyle,f="square"!==b.linecap,g=this.getGraphPath(),h=b.negativeColor;h&&c.push(["graphNeg",
h]);t(c,function(c,h){var l=c[0],m=a[l];m?(Ia(m),m.animate({d:g})):d&&g.length&&(m={stroke:c[1],"stroke-width":d,fill:"none",zIndex:1},e?m.dashstyle=e:f&&(m["stroke-linecap"]=m["stroke-linejoin"]="round"),a[l]=a.chart.renderer.path(g).attr(m).add(a.group).shadow(!h&&b.shadow))})},clipNeg:function(){var a=this.options,b=this.chart,c=b.renderer,d=a.negativeColor||a.negativeFillColor,e,f=this.graph,g=this.area,h=this.posClip,k=this.negClip;e=b.chartWidth;var m=b.chartHeight,l=x(e,m),n=this.yAxis;d&&
(f||g)&&(d=B(n.toPixels(a.threshold||0,!0)),0>d&&(l-=d),a={x:0,y:0,width:l,height:d},l={x:0,y:d,width:l,height:l},b.inverted&&(a.height=l.y=b.plotWidth-d,c.isVML&&(a={x:b.plotWidth-d-b.plotLeft,y:0,width:e,height:m},l={x:d+b.plotLeft-e,y:0,width:b.plotLeft+d,height:e})),n.reversed?(b=l,e=a):(b=a,e=l),h?(h.animate(b),k.animate(e)):(this.posClip=h=c.clipRect(b),this.negClip=k=c.clipRect(e),f&&this.graphNeg&&(f.clip(h),this.graphNeg.clip(k)),g&&(g.clip(h),this.areaNeg.clip(k))))},invertGroups:function(){function a(){var a=
{width:b.yAxis.len,height:b.xAxis.len};t(["group","markerGroup"],function(c){b[c]&&b[c].attr(a).invert()})}var b=this,c=b.chart;b.xAxis&&(L(c,"resize",a),L(b,"destroy",function(){T(c,"resize",a)}),a(),b.invertGroups=a)},plotGroup:function(a,b,c,d,e){var f=this[a],g=!f;g&&(this[a]=f=this.chart.renderer.g(b).attr({visibility:c,zIndex:d||.1}).add(e));f[g?"attr":"animate"](this.getPlotBox());return f},getPlotBox:function(){var a=this.chart,b=this.xAxis,c=this.yAxis;a.inverted&&(b=c,c=this.xAxis);return{translateX:b?
b.left:a.plotLeft,translateY:c?c.top:a.plotTop,scaleX:1,scaleY:1}},render:function(){var a=this,b=a.chart,c,d=a.options,e=(c=d.animation)&&!!a.animate&&b.renderer.isSVG&&l(c.duration,500)||0,f=a.visible?"visible":"hidden",g=d.zIndex,h=a.hasRendered,k=b.seriesGroup;c=a.plotGroup("group","series",f,g,k);a.markerGroup=a.plotGroup("markerGroup","markers",f,g,k);e&&a.animate(!0);a.getAttribs();c.inverted=a.isCartesian?b.inverted:!1;a.drawGraph&&(a.drawGraph(),a.clipNeg());t(a.points,function(a){a.redraw&&
a.redraw()});a.drawDataLabels&&a.drawDataLabels();a.visible&&a.drawPoints();a.drawTracker&&!1!==a.options.enableMouseTracking&&a.drawTracker();b.inverted&&a.invertGroups();!1===d.clip||a.sharedClipKey||h||c.clip(b.clipRect);e&&a.animate();h||(e?a.animationTimeout=setTimeout(function(){a.afterAnimate()},e):a.afterAnimate());a.isDirty=a.isDirtyData=!1;a.hasRendered=!0},redraw:function(){var a=this.chart,b=this.isDirtyData,c=this.group,d=this.xAxis,e=this.yAxis;c&&(a.inverted&&c.attr({width:a.plotWidth,
height:a.plotHeight}),c.animate({translateX:l(d&&d.left,a.plotLeft),translateY:l(e&&e.top,a.plotTop)}));this.translate();this.setTooltipPoints&&this.setTooltipPoints(!0);this.render();b&&M(this,"updatedData")}};var tb=Pa(Oa);pa.line=tb;u(ba,{Axis:ya,Chart:Fa,Color:qa,Point:Da,Tick:ia,Renderer:ra,Series:Oa,SVGElement:I,SVGRenderer:ra,arrayMin:ua,arrayMax:na,charts:ga,dateFormat:ta,format:sa,pathAnim:Ha,getOptions:function(){return F},hasBidiBug:mb,isTouchDevice:bb,numberFormat:$,seriesTypes:pa,setOptions:function(a){F=
A(!0,F,a);Ra();return F},addEvent:L,removeEvent:T,createElement:ma,discardElement:wa,css:P,each:t,extend:u,map:fb,merge:A,pick:l,splat:la,extendClass:Pa,pInt:s,wrap:Qa,svg:Q,canvas:Z,vml:!Q&&!Z,product:"Highcharts 4.0.4",version:"/Highstock 2.0.4"})})(); 