function rtrim(d){return d.replace(/..$/,"")}function _n(d,e,b){return 1==b?d:e}function GetPropertyByString(d){for(var d=d.split("."),e=window[d[0]],b=1,a=d.length;b<a;b++)e=e[d[b]];return e}
function fergcorp_countdownTimer_js(){jQuery("abbr.fergcorp_countdownTimer_event_time").each(function(){var d=new Date,e=new Date(1E3*GetPropertyByString("fergcorp_countdown_timer_jsEvents."+this.id));0>e-d?this.innerHTML=sprintf(fergcorp_countdown_timer_js_lang.agotime,fergcorp_countdownTimer_fuzzyDate(d,e,fergcorp_countdown_timer_options)):0<=e-d&&(this.innerHTML=sprintf(fergcorp_countdown_timer_js_lang.intime,fergcorp_countdownTimer_fuzzyDate(e,d,fergcorp_countdown_timer_options)))});window.setTimeout("fergcorp_countdownTimer_js()",
1E3)}
function fergcorp_countdownTimer_fuzzyDate(d,e,b){var a=0,i=!1,k=0,f="",k=e.getFullYear(),n=e.getMonth()+1,c=e.getDate(),g=e.getHours(),h=e.getMinutes(),l=e.getSeconds(),m=d.getFullYear(),j=d.getMonth()+1,o=d.getDate(),p=d.getHours(),q=d.getMinutes(),r=d.getSeconds(),m=m-k,j=j-n,c=o-c,g=p-g,h=q-h,l=r-l;0>l&&(h--,l=60+l);0>h&&(g--,h=60+h);0>g&&(c--,g=24+g);0>c&&(j--,c=c+32-(new Date(k,n-1,32)).getDate());0>j&&(m--,j+=12);if(parseInt(b.showYear)){if(i||!parseInt(b.stripZero)||m)f='<span class="fergcorp_countdownTimer_year fergcorp_countdownTimer_timeUnit">'+sprintf(_n(fergcorp_countdown_timer_js_lang.year,
fergcorp_countdown_timer_js_lang.years,m),m)+"</span> ",i=!0}else a=31536E3*m;if(parseInt(b.showMonth)){if(i||!parseInt(b.stripZero)||j+parseInt(a/2628E3))j+=parseInt(a/2628E3),f=f+'<span class="fergcorp_countdownTimer_month fergcorp_countdownTimer_timeUnit">'+sprintf(_n(fergcorp_countdown_timer_js_lang.month,fergcorp_countdown_timer_js_lang.months,j),j)+"</span> ",a-=2628E3*parseInt(a/2628E3),i=!0}else k=parseInt(d.getTime()-e.getTime())/1E3,parseInt(b.showYear)&&(k-=31536E3*m),resultantWeek=0,c=
parseInt(k/86400),g=parseInt((k-86400*c)/3600),h=parseInt((k-86400*c-3600*g)/60),l=parseInt(k-86400*c-3600*g-60*h),a=0;if(parseInt(b.showWeek)&&(i||!parseInt(b.stripZero)||parseInt((c+parseInt(a/86400))/7)))c+=parseInt(a/86400),f=f+'<span class="fergcorp_countdownTimer_week fergcorp_countdownTimer_timeUnit">'+sprintf(_n(fergcorp_countdown_timer_js_lang.week,fergcorp_countdown_timer_js_lang.weeks,parseInt((c+parseInt(a/86400))/7)),parseInt((c+parseInt(a/86400))/7))+"</span> ",a-=86400*parseInt(a/86400),
c-=7*parseInt((c+parseInt(a/86400))/7),i=!0;if(parseInt(b.showDay)){if(i||!parseInt(b.stripZero)||c+parseInt(a/86400))c+=parseInt(a/86400),f=f+'<span class="fergcorp_countdownTimer_day fergcorp_countdownTimer_timeUnit">'+sprintf(_n(fergcorp_countdown_timer_js_lang.day,fergcorp_countdown_timer_js_lang.days,c),c)+"</span> ",a-=86400*parseInt(a/86400),i=!0}else a+=86400*c;if(parseInt(b.showHour)){if(i||!parseInt(b.stripZero)||g+parseInt(a/3600))g+=parseInt(a/3600),f=f+'<span class="fergcorp_countdownTimer_hour fergcorp_countdownTimer_timeUnit">'+
sprintf(_n(fergcorp_countdown_timer_js_lang.hour,fergcorp_countdown_timer_js_lang.hours,g),g)+"<span> ",a-=3600*parseInt(a/3600),i=!0}else a+=3600*g;if(parseInt(b.showMinute)){if(i||!parseInt(b.stripZero)||h+parseInt(a/60))h+=parseInt(a/60),f=f+'<span class="fergcorp_countdownTimer_minute fergcorp_countdownTimer_timeUnit">'+sprintf(_n(fergcorp_countdown_timer_js_lang.minute,fergcorp_countdown_timer_js_lang.minutes,h),h)+"</span> ",a-=60*parseInt(a/60)}else a+=60*h;parseInt(b.showSecond)&&(l+=a,f=
f+'<span class="fergcorp_countdownTimer_second fergcorp_countdownTimer_timeUnit">'+sprintf(_n(fergcorp_countdown_timer_js_lang.second,fergcorp_countdown_timer_js_lang.seconds,l),l)+"</span> ");""==f&&(f=parseInt(b.showSecond)?'<span class="fergcorp_countdownTimer_second fergcorp_countdownTimer_timeUnit">'+sprintf(fergcorp_countdown_timer_js_lang.seconds,0)+"</span> ":parseInt(b.showMinute)?'<span class="fergcorp_countdownTimer_minute fergcorp_countdownTimer_timeUnit">'+sprintf(fergcorp_countdown_timer_js_lang.minutes,
0)+"</span> ":parseInt(b.showHour)?'<span class="fergcorp_countdownTimer_hour fergcorp_countdownTimer_timeUnit">'+sprintf(fergcorp_countdown_timer_js_lang.hours,0)+"</span> ":parseInt(b.showDay)?'<span class="fergcorp_countdownTimer_day fergcorp_countdownTimer_timeUnit">'+sprintf(fergcorp_countdown_timer_js_lang.days,0)+"</span> ":parseInt(b.showWeek)?'<span class="fergcorp_countdownTimer_week fergcorp_countdownTimer_timeUnit">'+sprintf(fergcorp_countdown_timer_js_lang.weeks,0)+"</span> ":parseInt(b.showMonth)?
'<span class="fergcorp_countdownTimer_month fergcorp_countdownTimer_timeUnit">'+sprintf(fergcorp_countdown_timer_js_lang.months,0)+"</span> ":'<span class="fergcorp_countdownTimer_year fergcorp_countdownTimer_timeUnit">'+sprintf(fergcorp_countdown_timer_js_lang.years,0)+"</span> ");return f.replace(/(, ?<\/span> *)$/,"</span>")}fergcorp_countdownTimer_js();